extends Node

const DEFAULT_LOCALE := "zh_TW"
const SUPPORTED_LOCALES := ["en", "ja", "ko", "es", "pt", "ru", "zh_CN", "zh_TW"]

const TEXT := {
	"en": {
		"game.title": "Cursed Curio Shop",
		"ui.start_day": "Start Day",
		"ui.quit": "Quit",
		"ui.inspect_prompt": "Press E to inspect the waiting oddity",
		"ui.run_status": "Day %d/%d | Cash %d | Reputation %d",
		"ui.shop_ledger": "Shop Ledger",
		"ui.no_appraisals": "No appraisals filed yet.",
		"ui.ledger_entry": "Day %d: %s -> %s",
		"ui.result_detail_title": "Appraisal Detail %d/%d",
		"ui.result_detail_empty": "No appraisal detail yet.",
		"ui.result_detail_body": "Oddity: %s\nDecision: %s\nOutcome: %s\nCash: %+d\nReputation: %+d\nConsequence: %s",
		"ui.back_to_shop": "Back to Shop",
		"ui.magnifier": "Magnifier",
		"ui.uv_lamp": "UV Lamp",
		"ui.thermometer": "Thermometer",
		"ui.temperature": "Temperature: %.1f C",
		"ui.appraisal_notes": "Appraisal Notes",
		"ui.note_mag": "- Mag: %s",
		"ui.note_uv": "- UV: %s",
		"ui.note_temp": "- Temp: %s",
		"ui.sell": "Sell",
		"ui.seal": "Seal",
		"ui.discard": "Discard",
		"ui.detail_previous": "Previous",
		"ui.detail_next": "Next",
		"decision.sell": "Sell",
		"decision.seal": "Seal",
		"decision.discard": "Discard",
		"ui.correct_result": "Correct: %s is handled safely.",
		"ui.wrong_result": "Wrong: %s should be %s, not %s.",
		"ui.cash_delta": "Cash: %+d",
		"ui.reputation_delta": "Reputation: %+d",
		"ui.next_day": "Next Day",
		"ui.return_to_menu": "Return to Menu",
		"ui.run_summary": "Run Summary",
		"ui.handled_count": "Handled: %d/%d oddities",
		"ui.final_cash": "Final Cash: %d",
		"ui.final_reputation": "Final Reputation: %d",
		"ui.last_report": "Last: %s",
		"ui.no_consequence": "No consequence recorded.",
		"outcome.correct": "Correct handling",
		"outcome.cursed_sale": "Cursed sale",
		"outcome.uncontained_discard": "Uncontained discard",
		"outcome.bad_appraisal": "Bad appraisal",
		"fallback.customer_note": "Customer Note",
		"fallback.customer_body": "A customer is waiting for an appraisal.",
		"fallback.risk_hint": "Risk hint: unknown",
		"fallback.consequence": "The customer files the appraisal note without comment.",
		"fallback.wrong_event": "%s disturbs the shop after the bad appraisal.",
		"item.oddity_0001.display_name": "Whispering Teacup",
		"item.oddity_0001.description": "A white porcelain teacup that stays unnaturally cold even under bright shop lamps.",
		"item.oddity_0001.magnifier_clue": "Hairline cracks form a faint spiral around the bowl.",
		"item.oddity_0001.uv_clue": "A hidden ring-shaped mark glows blue near the rim.",
		"item.oddity_0001.thermometer_clue": "The cup reads far below room temperature.",
		"item.oddity_0001.wrong_event_text": "If sold, the buyer returns with frostbite and the shop loses reputation.",
		"item.oddity_0002.display_name": "Mirror Coin",
		"item.oddity_0002.description": "A tarnished silver coin whose face reflects a room one second out of sync.",
		"item.oddity_0002.magnifier_clue": "Fine scratches form a deliberate appraisal mark.",
		"item.oddity_0002.uv_clue": "A hidden blue mark appears under UV light.",
		"item.oddity_0002.thermometer_clue": "The reading is inconsistent with the room.",
		"item.oddity_0002.wrong_event_text": "A minor abnormal event is queued for the shop.",
		"item.oddity_0003.display_name": "Ashen Music Box",
		"item.oddity_0003.description": "A scorched music box whose cylinder clicks even when the lid is shut.",
		"item.oddity_0003.magnifier_clue": "Fine scratches form a deliberate appraisal mark.",
		"item.oddity_0003.uv_clue": "A hidden blue mark appears under UV light.",
		"item.oddity_0003.thermometer_clue": "The reading is inconsistent with the room.",
		"item.oddity_0003.wrong_event_text": "A minor abnormal event is queued for the shop.",
		"customer.oddity_0001.title": "Customer Note: Shivering Heiress",
		"customer.oddity_0001.body": "A wrapped teacup arrived before dawn. The courier refused to touch it twice.",
		"customer.oddity_0001.risk_hint": "Risk hint: cold transfer",
		"customer.oddity_0002.title": "Customer Note: Clockmaker",
		"customer.oddity_0002.body": "A coin was found in a locked till, reflecting a room that is not there.",
		"customer.oddity_0002.risk_hint": "Risk hint: delayed reflection",
		"customer.oddity_0003.title": "Customer Note: Estate Executor",
		"customer.oddity_0003.body": "This music box played during the inventory, though no key was wound.",
		"customer.oddity_0003.risk_hint": "Risk hint: self-playing mechanism",
		"consequence.oddity_0001.seal": "The customer leaves without the cup",
		"consequence.oddity_0001.sell": "The buyer complains that frost crept across the receipt",
		"consequence.oddity_0001.discard": "The discarded cup returns to the doorstep with fresh ice inside.",
		"consequence.oddity_0002.seal": "The clockmaker accepts the sealed packet and stops hearing the delayed echo.",
		"consequence.oddity_0002.sell": "The buyer pays quickly, but their reflection lags behind them at the door.",
		"consequence.oddity_0002.discard": "The coin rolls back under the counter after the bell rings once.",
		"consequence.oddity_0003.seal": "The estate executor notes that the tune finally stops in the hallway.",
		"consequence.oddity_0003.sell": "The buyer reports music from an empty nursery after midnight.",
		"consequence.oddity_0003.discard": "The music box is removed quietly",
		"ending.frost_sale.title": "Bad Ending: Frost Sale",
	},
	"ja": {
		"game.title": "呪われた骨董店",
		"ui.start_day": "一日を始める",
		"ui.quit": "終了",
		"ui.inspect_prompt": "Eキーで待機中の奇物を鑑定",
		"ui.run_status": "%d/%d日目 | 所持金 %d | 評判 %d",
		"ui.shop_ledger": "店の台帳",
		"ui.no_appraisals": "鑑定記録はまだありません。",
		"ui.ledger_entry": "%d日目: %s -> %s",
		"ui.result_detail_title": "鑑定詳細 %d/%d",
		"ui.result_detail_empty": "鑑定詳細はまだありません。",
		"ui.result_detail_body": "奇物: %s\n判断: %s\n結果: %s\n現金: %+d\n評判: %+d\n後日談: %s",
		"ui.back_to_shop": "店に戻る",
		"ui.magnifier": "拡大鏡",
		"ui.uv_lamp": "UVランプ",
		"ui.thermometer": "温度計",
		"ui.temperature": "温度: %.1f C",
		"ui.appraisal_notes": "鑑定メモ",
		"ui.note_mag": "- 拡大: %s",
		"ui.note_uv": "- UV: %s",
		"ui.note_temp": "- 温度: %s",
		"ui.sell": "売る",
		"ui.seal": "封印",
		"ui.discard": "廃棄",
		"ui.detail_previous": "前へ",
		"ui.detail_next": "次へ",
		"decision.sell": "売却",
		"decision.seal": "封印",
		"decision.discard": "廃棄",
		"ui.correct_result": "正解: %s は安全に処理された。",
		"ui.wrong_result": "誤り: %s は %s すべきで、%s ではない。",
		"ui.cash_delta": "所持金: %+d",
		"ui.reputation_delta": "評判: %+d",
		"ui.next_day": "次の日",
		"ui.return_to_menu": "メニューへ戻る",
		"ui.run_summary": "プレイ結果",
		"ui.handled_count": "処理数: %d/%d 個",
		"ui.final_cash": "最終所持金: %d",
		"ui.final_reputation": "最終評判: %d",
		"ui.last_report": "最後: %s",
		"ui.no_consequence": "結果記録なし。",
		"outcome.correct": "正しい処理",
		"outcome.cursed_sale": "呪われた販売",
		"outcome.uncontained_discard": "未封印の廃棄",
		"outcome.bad_appraisal": "誤鑑定",
		"fallback.customer_note": "顧客メモ",
		"fallback.customer_body": "顧客が鑑定を待っている。",
		"fallback.risk_hint": "危険の手掛かり: 不明",
		"fallback.consequence": "顧客は何も言わず鑑定書をしまった。",
		"fallback.wrong_event": "%s が誤鑑定のあと店を乱す。",
		"item.oddity_0001.display_name": "囁くティーカップ",
		"item.oddity_0001.description": "明るい店内の灯りの下でも不自然に冷たい白磁のティーカップ。",
		"item.oddity_0001.magnifier_clue": "細いひびが器の周囲に淡い渦を描いている。",
		"item.oddity_0001.uv_clue": "縁の近くに隠れた輪状の印が青く光る。",
		"item.oddity_0001.thermometer_clue": "カップは室温を大きく下回っている。",
		"item.oddity_0001.wrong_event_text": "売却すると、買い手は凍傷を負って戻り、店の評判が落ちる。",
		"item.oddity_0002.display_name": "鏡映りの硬貨",
		"item.oddity_0002.description": "表面が一秒遅れの部屋を映す、くすんだ銀貨。",
		"item.oddity_0002.magnifier_clue": "細かな傷が意図的な鑑定印を形作っている。",
		"item.oddity_0002.uv_clue": "UV光の下で隠れた青い印が現れる。",
		"item.oddity_0002.thermometer_clue": "測定値が室温と一致しない。",
		"item.oddity_0002.wrong_event_text": "店内で小さな異常事象が発生する。",
		"item.oddity_0003.display_name": "灰かぶりのオルゴール",
		"item.oddity_0003.description": "蓋を閉じていてもシリンダーが鳴る、焦げたオルゴール。",
		"item.oddity_0003.magnifier_clue": "細かな傷が意図的な鑑定印を形作っている。",
		"item.oddity_0003.uv_clue": "UV光の下で隠れた青い印が現れる。",
		"item.oddity_0003.thermometer_clue": "測定値が室温と一致しない。",
		"item.oddity_0003.wrong_event_text": "店内で小さな異常事象が発生する。",
		"customer.oddity_0001.title": "顧客メモ: 震える相続人",
		"customer.oddity_0001.body": "夜明け前、包まれたティーカップが届いた。配達人は二度触るのを拒んだ。",
		"customer.oddity_0001.risk_hint": "危険の手掛かり: 冷気の移動",
		"customer.oddity_0002.title": "顧客メモ: 時計職人",
		"customer.oddity_0002.body": "鍵のかかった金庫で見つかった硬貨は、存在しない部屋を映していた。",
		"customer.oddity_0002.risk_hint": "危険の手掛かり: 遅れる反射",
		"customer.oddity_0003.title": "顧客メモ: 遺産執行人",
		"customer.oddity_0003.body": "誰もぜんまいを巻いていないのに、棚卸し中にこのオルゴールが鳴った。",
		"customer.oddity_0003.risk_hint": "危険の手掛かり: 自動演奏機構",
		"consequence.oddity_0001.seal": "顧客はカップを持たずに帰った",
		"consequence.oddity_0001.sell": "買い手は領収書に霜が広がったと苦情を言う",
		"consequence.oddity_0001.discard": "捨てたカップが新しい氷を抱えて玄関先に戻る。",
		"consequence.oddity_0002.seal": "時計職人は封印包みを受け取り、遅れた反響を聞かなくなった。",
		"consequence.oddity_0002.sell": "買い手は急いで支払うが、戸口で反射だけが遅れている。",
		"consequence.oddity_0002.discard": "ベルが一度鳴った後、硬貨はカウンターの下へ転がり戻る。",
		"consequence.oddity_0003.seal": "遺産執行人は、廊下で曲がようやく止んだと記録した。",
		"consequence.oddity_0003.sell": "買い手は真夜中に空の子供部屋から音楽が聞こえると報告する。",
		"consequence.oddity_0003.discard": "オルゴールは静かに撤去された",
		"ending.frost_sale.title": "バッドエンド: 霜の販売",
	},
	"ko": {
		"game.title": "저주받은 골동품점",
		"ui.start_day": "하루 시작",
		"ui.quit": "종료",
		"ui.inspect_prompt": "E를 눌러 대기 중인 기물을 감정",
		"ui.run_status": "%d/%d일 | 현금 %d | 평판 %d",
		"ui.shop_ledger": "상점 장부",
		"ui.no_appraisals": "아직 감정 기록이 없습니다.",
		"ui.ledger_entry": "%d일: %s -> %s",
		"ui.result_detail_title": "감정 세부 정보 %d/%d",
		"ui.result_detail_empty": "아직 감정 세부 정보가 없습니다.",
		"ui.result_detail_body": "기물: %s\n결정: %s\n결과: %s\n현금: %+d\n평판: %+d\n후속 기록: %s",
		"ui.back_to_shop": "상점으로",
		"ui.magnifier": "돋보기",
		"ui.uv_lamp": "UV 램프",
		"ui.thermometer": "온도계",
		"ui.temperature": "온도: %.1f C",
		"ui.appraisal_notes": "감정 노트",
		"ui.note_mag": "- 확대: %s",
		"ui.note_uv": "- UV: %s",
		"ui.note_temp": "- 온도: %s",
		"ui.sell": "판매",
		"ui.seal": "봉인",
		"ui.discard": "폐기",
		"ui.detail_previous": "이전",
		"ui.detail_next": "다음",
		"decision.sell": "판매",
		"decision.seal": "봉인",
		"decision.discard": "폐기",
		"ui.correct_result": "정답: %s 이 안전하게 처리되었습니다.",
		"ui.wrong_result": "오답: %s 은 %s 해야 하며 %s 하면 안 됩니다.",
		"ui.cash_delta": "현금: %+d",
		"ui.reputation_delta": "평판: %+d",
		"ui.next_day": "다음 날",
		"ui.return_to_menu": "메뉴로",
		"ui.run_summary": "진행 요약",
		"ui.handled_count": "처리: %d/%d 개",
		"ui.final_cash": "최종 현금: %d",
		"ui.final_reputation": "최종 평판: %d",
		"ui.last_report": "마지막: %s",
		"ui.no_consequence": "기록된 결과가 없습니다.",
		"outcome.correct": "올바른 처리",
		"outcome.cursed_sale": "저주받은 판매",
		"outcome.uncontained_discard": "봉인 없는 폐기",
		"outcome.bad_appraisal": "잘못된 감정",
		"fallback.customer_note": "고객 메모",
		"fallback.customer_body": "고객이 감정을 기다리고 있습니다.",
		"fallback.risk_hint": "위험 단서: 알 수 없음",
		"fallback.consequence": "고객은 말없이 감정 기록을 보관합니다.",
		"fallback.wrong_event": "%s 이 잘못된 감정 뒤 상점을 어지럽힙니다.",
		"item.oddity_0001.display_name": "속삭이는 찻잔",
		"item.oddity_0001.description": "밝은 상점 조명 아래에서도 비정상적으로 차가운 흰 도자기 찻잔.",
		"item.oddity_0001.magnifier_clue": "가는 균열이 잔 둘레에 희미한 소용돌이를 이룹니다.",
		"item.oddity_0001.uv_clue": "가장자리 근처 숨은 고리 표식이 푸르게 빛납니다.",
		"item.oddity_0001.thermometer_clue": "찻잔은 실온보다 훨씬 낮게 측정됩니다.",
		"item.oddity_0001.wrong_event_text": "판매하면 구매자가 동상에 걸려 돌아오고 상점 평판이 떨어집니다.",
		"item.oddity_0002.display_name": "거울 동전",
		"item.oddity_0002.description": "얼굴이 1초 늦은 방을 비추는 변색된 은화.",
		"item.oddity_0002.magnifier_clue": "가는 흠집이 의도적인 감정 표식을 이룹니다.",
		"item.oddity_0002.uv_clue": "UV 빛 아래 숨은 푸른 표식이 나타납니다.",
		"item.oddity_0002.thermometer_clue": "측정값이 방 온도와 맞지 않습니다.",
		"item.oddity_0002.wrong_event_text": "상점에 작은 이상 현상이 예정됩니다.",
		"item.oddity_0003.display_name": "재 묻은 오르골",
		"item.oddity_0003.description": "뚜껑이 닫혀도 원통이 딸깍거리는 그을린 오르골.",
		"item.oddity_0003.magnifier_clue": "가는 흠집이 의도적인 감정 표식을 이룹니다.",
		"item.oddity_0003.uv_clue": "UV 빛 아래 숨은 푸른 표식이 나타납니다.",
		"item.oddity_0003.thermometer_clue": "측정값이 방 온도와 맞지 않습니다.",
		"item.oddity_0003.wrong_event_text": "상점에 작은 이상 현상이 예정됩니다.",
		"customer.oddity_0001.title": "고객 메모: 떨리는 상속녀",
		"customer.oddity_0001.body": "동트기 전 포장된 찻잔이 도착했습니다. 배달원은 두 번 만지기를 거부했습니다.",
		"customer.oddity_0001.risk_hint": "위험 단서: 냉기 전이",
		"customer.oddity_0002.title": "고객 메모: 시계공",
		"customer.oddity_0002.body": "잠긴 금고에서 발견된 동전은 존재하지 않는 방을 비추고 있었습니다.",
		"customer.oddity_0002.risk_hint": "위험 단서: 지연된 반사",
		"customer.oddity_0003.title": "고객 메모: 유산 집행인",
		"customer.oddity_0003.body": "태엽을 감지 않았는데도 재고 조사 중 이 오르골이 연주되었습니다.",
		"customer.oddity_0003.risk_hint": "위험 단서: 자동 연주 장치",
		"consequence.oddity_0001.seal": "고객은 찻잔 없이 떠납니다",
		"consequence.oddity_0001.sell": "구매자가 영수증에 서리가 번졌다고 항의합니다",
		"consequence.oddity_0001.discard": "버린 찻잔이 새 얼음을 담고 문 앞에 돌아옵니다.",
		"consequence.oddity_0002.seal": "시계공은 봉인된 꾸러미를 받고 지연된 메아리를 더 듣지 않습니다.",
		"consequence.oddity_0002.sell": "구매자는 급히 돈을 내지만 문가에서 반사만 뒤처집니다.",
		"consequence.oddity_0002.discard": "종이 한 번 울린 뒤 동전은 카운터 밑으로 굴러 돌아옵니다.",
		"consequence.oddity_0003.seal": "유산 집행인은 복도에서 마침내 음악이 멈췄다고 기록합니다.",
		"consequence.oddity_0003.sell": "구매자는 자정 이후 빈 아이 방에서 음악이 들린다고 보고합니다.",
		"consequence.oddity_0003.discard": "오르골은 조용히 치워졌습니다",
		"ending.frost_sale.title": "나쁜 결말: 서리 판매",
	},
	"es": {
		"game.title": "Tienda de Curios Malditos",
		"ui.start_day": "Comenzar dia",
		"ui.quit": "Salir",
		"ui.inspect_prompt": "Pulsa E para inspeccionar la rareza en espera",
		"ui.run_status": "Dia %d/%d | Dinero %d | Reputacion %d",
		"ui.shop_ledger": "Libro de la tienda",
		"ui.no_appraisals": "Aun no hay tasaciones archivadas.",
		"ui.ledger_entry": "Dia %d: %s -> %s",
		"ui.result_detail_title": "Detalle de tasacion %d/%d",
		"ui.result_detail_empty": "Aun no hay detalle de tasacion.",
		"ui.result_detail_body": "Rareza: %s\nDecision: %s\nResultado: %s\nEfectivo: %+d\nReputacion: %+d\nConsecuencia: %s",
		"ui.back_to_shop": "Volver a la tienda",
		"ui.magnifier": "Lupa",
		"ui.uv_lamp": "Lampara UV",
		"ui.thermometer": "Termometro",
		"ui.temperature": "Temperatura: %.1f C",
		"ui.appraisal_notes": "Notas de tasacion",
		"ui.note_mag": "- Lupa: %s",
		"ui.note_uv": "- UV: %s",
		"ui.note_temp": "- Temp: %s",
		"ui.sell": "Vender",
		"ui.seal": "Sellar",
		"ui.discard": "Desechar",
		"ui.detail_previous": "Anterior",
		"ui.detail_next": "Siguiente",
		"decision.sell": "Vender",
		"decision.seal": "Sellar",
		"decision.discard": "Desechar",
		"ui.correct_result": "Correcto: %s se manejo con seguridad.",
		"ui.wrong_result": "Error: %s debia ser %s, no %s.",
		"ui.cash_delta": "Dinero: %+d",
		"ui.reputation_delta": "Reputacion: %+d",
		"ui.next_day": "Dia siguiente",
		"ui.return_to_menu": "Volver al menu",
		"ui.run_summary": "Resumen",
		"ui.handled_count": "Tratadas: %d/%d rarezas",
		"ui.final_cash": "Dinero final: %d",
		"ui.final_reputation": "Reputacion final: %d",
		"ui.last_report": "Ultimo: %s",
		"ui.no_consequence": "No hay consecuencia registrada.",
		"outcome.correct": "Manejo correcto",
		"outcome.cursed_sale": "Venta maldita",
		"outcome.uncontained_discard": "Desecho sin contener",
		"outcome.bad_appraisal": "Mala tasacion",
		"fallback.customer_note": "Nota del cliente",
		"fallback.customer_body": "Un cliente espera una tasacion.",
		"fallback.risk_hint": "Pista de riesgo: desconocida",
		"fallback.consequence": "El cliente archiva la nota sin comentario.",
		"fallback.wrong_event": "%s perturba la tienda tras la mala tasacion.",
		"item.oddity_0001.display_name": "Taza susurrante",
		"item.oddity_0001.description": "Una taza de porcelana blanca que permanece anormalmente fria incluso bajo las lamparas de la tienda.",
		"item.oddity_0001.magnifier_clue": "Grietas finas forman una espiral tenue alrededor del cuenco.",
		"item.oddity_0001.uv_clue": "Una marca circular oculta brilla azul cerca del borde.",
		"item.oddity_0001.thermometer_clue": "La taza marca muy por debajo de la temperatura ambiente.",
		"item.oddity_0001.wrong_event_text": "Si se vende, el comprador vuelve con congelacion y la tienda pierde reputacion.",
		"item.oddity_0002.display_name": "Moneda espejo",
		"item.oddity_0002.description": "Una moneda de plata opaca cuyo rostro refleja una habitacion con un segundo de retraso.",
		"item.oddity_0002.magnifier_clue": "Rayas finas forman una marca de tasacion deliberada.",
		"item.oddity_0002.uv_clue": "Una marca azul oculta aparece bajo luz UV.",
		"item.oddity_0002.thermometer_clue": "La lectura no coincide con la habitacion.",
		"item.oddity_0002.wrong_event_text": "Un evento anomalo menor queda preparado para la tienda.",
		"item.oddity_0003.display_name": "Caja musical cenicienta",
		"item.oddity_0003.description": "Una caja musical quemada cuyo cilindro hace clic incluso con la tapa cerrada.",
		"item.oddity_0003.magnifier_clue": "Rayas finas forman una marca de tasacion deliberada.",
		"item.oddity_0003.uv_clue": "Una marca azul oculta aparece bajo luz UV.",
		"item.oddity_0003.thermometer_clue": "La lectura no coincide con la habitacion.",
		"item.oddity_0003.wrong_event_text": "Un evento anomalo menor queda preparado para la tienda.",
		"customer.oddity_0001.title": "Nota del cliente: heredera temblorosa",
		"customer.oddity_0001.body": "Una taza envuelta llego antes del amanecer. El mensajero se nego a tocarla dos veces.",
		"customer.oddity_0001.risk_hint": "Pista de riesgo: transferencia fria",
		"customer.oddity_0002.title": "Nota del cliente: relojero",
		"customer.oddity_0002.body": "La moneda aparecio en una caja cerrada y refleja una habitacion que no existe.",
		"customer.oddity_0002.risk_hint": "Pista de riesgo: reflejo retrasado",
		"customer.oddity_0003.title": "Nota del cliente: albacea",
		"customer.oddity_0003.body": "La caja musical sono durante el inventario aunque nadie le dio cuerda.",
		"customer.oddity_0003.risk_hint": "Pista de riesgo: mecanismo automatico",
		"consequence.oddity_0001.seal": "El cliente se marcha sin la taza",
		"consequence.oddity_0001.sell": "El comprador se queja de que la escarcha cubrio el recibo",
		"consequence.oddity_0001.discard": "La taza desechada vuelve al umbral con hielo nuevo dentro.",
		"consequence.oddity_0002.seal": "El relojero acepta el paquete sellado y deja de oir el eco retrasado.",
		"consequence.oddity_0002.sell": "El comprador paga rapido, pero su reflejo se retrasa en la puerta.",
		"consequence.oddity_0002.discard": "La moneda rueda de vuelta bajo el mostrador tras una campanada.",
		"consequence.oddity_0003.seal": "El albacea anota que la melodia por fin se detiene en el pasillo.",
		"consequence.oddity_0003.sell": "El comprador informa de musica en una guarderia vacia despues de medianoche.",
		"consequence.oddity_0003.discard": "La caja musical se retira en silencio",
		"ending.frost_sale.title": "Final malo: venta helada",
	},
	"pt": {
		"game.title": "Loja de Curiosidades Amaldicoadas",
		"ui.start_day": "Iniciar dia",
		"ui.quit": "Sair",
		"ui.inspect_prompt": "Pressione E para inspecionar a curiosidade em espera",
		"ui.run_status": "Dia %d/%d | Dinheiro %d | Reputacao %d",
		"ui.shop_ledger": "Livro da loja",
		"ui.no_appraisals": "Nenhuma avaliacao arquivada ainda.",
		"ui.ledger_entry": "Dia %d: %s -> %s",
		"ui.result_detail_title": "Detalhe da avaliacao %d/%d",
		"ui.result_detail_empty": "Ainda nao ha detalhe de avaliacao.",
		"ui.result_detail_body": "Curio: %s\nDecisao: %s\nResultado: %s\nDinheiro: %+d\nReputacao: %+d\nConsequencia: %s",
		"ui.back_to_shop": "Voltar a loja",
		"ui.magnifier": "Lupa",
		"ui.uv_lamp": "Lampada UV",
		"ui.thermometer": "Termometro",
		"ui.temperature": "Temperatura: %.1f C",
		"ui.appraisal_notes": "Notas de avaliacao",
		"ui.note_mag": "- Lupa: %s",
		"ui.note_uv": "- UV: %s",
		"ui.note_temp": "- Temp: %s",
		"ui.sell": "Vender",
		"ui.seal": "Selar",
		"ui.discard": "Descartar",
		"ui.detail_previous": "Anterior",
		"ui.detail_next": "Proximo",
		"decision.sell": "Vender",
		"decision.seal": "Selar",
		"decision.discard": "Descartar",
		"ui.correct_result": "Correto: %s foi tratado com seguranca.",
		"ui.wrong_result": "Errado: %s deveria ser %s, nao %s.",
		"ui.cash_delta": "Dinheiro: %+d",
		"ui.reputation_delta": "Reputacao: %+d",
		"ui.next_day": "Proximo dia",
		"ui.return_to_menu": "Voltar ao menu",
		"ui.run_summary": "Resumo",
		"ui.handled_count": "Tratadas: %d/%d curiosidades",
		"ui.final_cash": "Dinheiro final: %d",
		"ui.final_reputation": "Reputacao final: %d",
		"ui.last_report": "Ultimo: %s",
		"ui.no_consequence": "Nenhuma consequencia registrada.",
		"outcome.correct": "Tratamento correto",
		"outcome.cursed_sale": "Venda amaldicoada",
		"outcome.uncontained_discard": "Descarte sem conter",
		"outcome.bad_appraisal": "Avaliacao ruim",
		"fallback.customer_note": "Nota do cliente",
		"fallback.customer_body": "Um cliente aguarda uma avaliacao.",
		"fallback.risk_hint": "Pista de risco: desconhecida",
		"fallback.consequence": "O cliente arquiva a nota sem comentario.",
		"fallback.wrong_event": "%s perturba a loja apos a avaliacao ruim.",
		"item.oddity_0001.display_name": "Xicara sussurrante",
		"item.oddity_0001.description": "Uma xicara de porcelana branca que permanece anormalmente fria mesmo sob as lampadas da loja.",
		"item.oddity_0001.magnifier_clue": "Rachaduras finas formam uma espiral fraca ao redor da tigela.",
		"item.oddity_0001.uv_clue": "Uma marca circular oculta brilha em azul perto da borda.",
		"item.oddity_0001.thermometer_clue": "A xicara marca muito abaixo da temperatura ambiente.",
		"item.oddity_0001.wrong_event_text": "Se vendida, o comprador volta com queimadura de frio e a loja perde reputacao.",
		"item.oddity_0002.display_name": "Moeda espelhada",
		"item.oddity_0002.description": "Uma moeda de prata escurecida cujo rosto reflete uma sala com um segundo de atraso.",
		"item.oddity_0002.magnifier_clue": "Riscos finos formam uma marca de avaliacao deliberada.",
		"item.oddity_0002.uv_clue": "Uma marca azul oculta aparece sob luz UV.",
		"item.oddity_0002.thermometer_clue": "A leitura nao combina com a sala.",
		"item.oddity_0002.wrong_event_text": "Um pequeno evento anomalo fica preparado para a loja.",
		"item.oddity_0003.display_name": "Caixa de musica cinzenta",
		"item.oddity_0003.description": "Uma caixa de musica chamuscada cujo cilindro estala mesmo com a tampa fechada.",
		"item.oddity_0003.magnifier_clue": "Riscos finos formam uma marca de avaliacao deliberada.",
		"item.oddity_0003.uv_clue": "Uma marca azul oculta aparece sob luz UV.",
		"item.oddity_0003.thermometer_clue": "A leitura nao combina com a sala.",
		"item.oddity_0003.wrong_event_text": "Um pequeno evento anomalo fica preparado para a loja.",
		"customer.oddity_0001.title": "Nota do cliente: herdeira tremula",
		"customer.oddity_0001.body": "Uma xicara embrulhada chegou antes do amanhecer. O entregador se recusou a toca-la duas vezes.",
		"customer.oddity_0001.risk_hint": "Pista de risco: transferencia fria",
		"customer.oddity_0002.title": "Nota do cliente: relojoeiro",
		"customer.oddity_0002.body": "Uma moeda foi encontrada em uma caixa trancada, refletindo uma sala que nao existe.",
		"customer.oddity_0002.risk_hint": "Pista de risco: reflexo atrasado",
		"customer.oddity_0003.title": "Nota do cliente: executor do espolio",
		"customer.oddity_0003.body": "Esta caixa de musica tocou durante o inventario, embora ninguem a tenha dado corda.",
		"customer.oddity_0003.risk_hint": "Pista de risco: mecanismo automatico",
		"consequence.oddity_0001.seal": "O cliente vai embora sem a xicara",
		"consequence.oddity_0001.sell": "O comprador reclama que a geada cobriu o recibo",
		"consequence.oddity_0001.discard": "A xicara descartada volta ao degrau com gelo novo dentro.",
		"consequence.oddity_0002.seal": "O relojoeiro aceita o pacote selado e para de ouvir o eco atrasado.",
		"consequence.oddity_0002.sell": "O comprador paga rapido, mas seu reflexo se atrasa na porta.",
		"consequence.oddity_0002.discard": "A moeda rola de volta para baixo do balcao depois de um toque.",
		"consequence.oddity_0003.seal": "O executor anota que a melodia finalmente para no corredor.",
		"consequence.oddity_0003.sell": "O comprador relata musica em um quarto infantil vazio depois da meia-noite.",
		"consequence.oddity_0003.discard": "A caixa de musica e removida em silencio",
		"ending.frost_sale.title": "Final ruim: venda congelada",
	},
	"ru": {
		"game.title": "Лавка проклятых редкостей",
		"ui.start_day": "Начать день",
		"ui.quit": "Выйти",
		"ui.inspect_prompt": "Нажмите E, чтобы осмотреть ожидающий предмет",
		"ui.run_status": "День %d/%d | Деньги %d | Репутация %d",
		"ui.shop_ledger": "Журнал лавки",
		"ui.no_appraisals": "Оценок пока нет.",
		"ui.ledger_entry": "День %d: %s -> %s",
		"ui.result_detail_title": "Детали оценки %d/%d",
		"ui.result_detail_empty": "Деталей оценки пока нет.",
		"ui.result_detail_body": "Диковина: %s\nРешение: %s\nИтог: %s\nДеньги: %+d\nРепутация: %+d\nПоследствие: %s",
		"ui.back_to_shop": "Вернуться в лавку",
		"ui.magnifier": "Лупа",
		"ui.uv_lamp": "УФ-лампа",
		"ui.thermometer": "Термометр",
		"ui.temperature": "Температура: %.1f C",
		"ui.appraisal_notes": "Заметки оценки",
		"ui.note_mag": "- Лупа: %s",
		"ui.note_uv": "- УФ: %s",
		"ui.note_temp": "- Темп.: %s",
		"ui.sell": "Продать",
		"ui.seal": "Запечатать",
		"ui.discard": "Выбросить",
		"ui.detail_previous": "Назад",
		"ui.detail_next": "Далее",
		"decision.sell": "Продать",
		"decision.seal": "Запечатать",
		"decision.discard": "Выбросить",
		"ui.correct_result": "Верно: %s обработан безопасно.",
		"ui.wrong_result": "Ошибка: %s нужно было %s, а не %s.",
		"ui.cash_delta": "Деньги: %+d",
		"ui.reputation_delta": "Репутация: %+d",
		"ui.next_day": "Следующий день",
		"ui.return_to_menu": "В меню",
		"ui.run_summary": "Итог забега",
		"ui.handled_count": "Обработано: %d/%d предметов",
		"ui.final_cash": "Итоговые деньги: %d",
		"ui.final_reputation": "Итоговая репутация: %d",
		"ui.last_report": "Последнее: %s",
		"ui.no_consequence": "Последствий не записано.",
		"outcome.correct": "Верная обработка",
		"outcome.cursed_sale": "Проклятая продажа",
		"outcome.uncontained_discard": "Выброшено без удержания",
		"outcome.bad_appraisal": "Плохая оценка",
		"fallback.customer_note": "Записка клиента",
		"fallback.customer_body": "Клиент ждет оценки.",
		"fallback.risk_hint": "Подсказка риска: неизвестно",
		"fallback.consequence": "Клиент молча подшивает оценку.",
		"fallback.wrong_event": "%s тревожит лавку после плохой оценки.",
		"item.oddity_0001.display_name": "Шепчущая чашка",
		"item.oddity_0001.description": "Белая фарфоровая чашка остается неестественно холодной даже под яркими лампами лавки.",
		"item.oddity_0001.magnifier_clue": "Тонкие трещины образуют слабую спираль вокруг чаши.",
		"item.oddity_0001.uv_clue": "Скрытая кольцевая метка у края светится синим под УФ.",
		"item.oddity_0001.thermometer_clue": "Чашка показывает температуру намного ниже комнатной.",
		"item.oddity_0001.wrong_event_text": "Если продать ее, покупатель вернется с обморожением, а репутация лавки упадет.",
		"item.oddity_0002.display_name": "Зеркальная монета",
		"item.oddity_0002.description": "Потускневшая серебряная монета отражает комнату с задержкой в одну секунду.",
		"item.oddity_0002.magnifier_clue": "Тонкие царапины образуют намеренную оценочную метку.",
		"item.oddity_0002.uv_clue": "Под УФ-светом проявляется скрытая синяя метка.",
		"item.oddity_0002.thermometer_clue": "Показания не совпадают с температурой комнаты.",
		"item.oddity_0002.wrong_event_text": "В лавке готовится небольшая аномалия.",
		"item.oddity_0003.display_name": "Пепельная музыкальная шкатулка",
		"item.oddity_0003.description": "Обгоревшая музыкальная шкатулка щелкает цилиндром даже с закрытой крышкой.",
		"item.oddity_0003.magnifier_clue": "Тонкие царапины образуют намеренную оценочную метку.",
		"item.oddity_0003.uv_clue": "Под УФ-светом проявляется скрытая синяя метка.",
		"item.oddity_0003.thermometer_clue": "Показания не совпадают с температурой комнаты.",
		"item.oddity_0003.wrong_event_text": "В лавке готовится небольшая аномалия.",
		"customer.oddity_0001.title": "Записка клиента: дрожащая наследница",
		"customer.oddity_0001.body": "Завернутая чашка прибыла до рассвета. Курьер отказался коснуться ее второй раз.",
		"customer.oddity_0001.risk_hint": "Подсказка риска: перенос холода",
		"customer.oddity_0002.title": "Записка клиента: часовщик",
		"customer.oddity_0002.body": "Монету нашли в запертом ящике; она отражает комнату, которой нет.",
		"customer.oddity_0002.risk_hint": "Подсказка риска: запаздывающее отражение",
		"customer.oddity_0003.title": "Записка клиента: душеприказчик",
		"customer.oddity_0003.body": "Эта шкатулка заиграла во время описи, хотя ключ никто не заводил.",
		"customer.oddity_0003.risk_hint": "Подсказка риска: самоиграющий механизм",
		"consequence.oddity_0001.seal": "Клиент уходит без чашки",
		"consequence.oddity_0001.sell": "Покупатель жалуется, что иней расползся по чеку",
		"consequence.oddity_0001.discard": "Выброшенная чашка возвращается к порогу с новым льдом внутри.",
		"consequence.oddity_0002.seal": "Часовщик принимает запечатанный пакет и больше не слышит запоздалое эхо.",
		"consequence.oddity_0002.sell": "Покупатель быстро платит, но его отражение отстает у двери.",
		"consequence.oddity_0002.discard": "После одного звонка монета выкатывается обратно под прилавок.",
		"consequence.oddity_0003.seal": "Душеприказчик отмечает, что мелодия в коридоре наконец стихла.",
		"consequence.oddity_0003.sell": "Покупатель сообщает о музыке из пустой детской после полуночи.",
		"consequence.oddity_0003.discard": "Шкатулку тихо убирают",
		"ending.frost_sale.title": "Плохая концовка: морозная продажа",
	},
	"zh_CN": {
		"game.title": "诅咒古物店",
		"ui.start_day": "开始一天",
		"ui.quit": "退出",
		"ui.inspect_prompt": "按 E 检查等待鉴定的异物",
		"ui.run_status": "第 %d/%d 天 | 现金 %d | 声誉 %d",
		"ui.shop_ledger": "店铺账本",
		"ui.no_appraisals": "尚无鉴定记录。",
		"ui.ledger_entry": "第 %d 天：%s -> %s",
		"ui.result_detail_title": "鉴定结果详情 %d/%d",
		"ui.result_detail_empty": "尚无鉴定结果详情。",
		"ui.result_detail_body": "异物：%s\n决策：%s\n结果：%s\n现金：%+d\n声望：%+d\n后果：%s",
		"ui.back_to_shop": "返回店铺",
		"ui.magnifier": "放大镜",
		"ui.uv_lamp": "紫外灯",
		"ui.thermometer": "温度计",
		"ui.temperature": "温度：%.1f C",
		"ui.appraisal_notes": "鉴定笔记",
		"ui.note_mag": "- 放大：%s",
		"ui.note_uv": "- UV：%s",
		"ui.note_temp": "- 温度：%s",
		"ui.sell": "出售",
		"ui.seal": "封印",
		"ui.discard": "丢弃",
		"ui.detail_previous": "上一笔",
		"ui.detail_next": "下一笔",
		"decision.sell": "出售",
		"decision.seal": "封存",
		"decision.discard": "丢弃",
		"ui.correct_result": "正确：%s 已安全处理。",
		"ui.wrong_result": "错误：%s 应该%s，而不是%s。",
		"ui.cash_delta": "现金：%+d",
		"ui.reputation_delta": "声誉：%+d",
		"ui.next_day": "下一天",
		"ui.return_to_menu": "返回菜单",
		"ui.run_summary": "流程总结",
		"ui.handled_count": "已处理：%d/%d 件异物",
		"ui.final_cash": "最终现金：%d",
		"ui.final_reputation": "最终声誉：%d",
		"ui.last_report": "最后记录：%s",
		"ui.no_consequence": "没有记录后果。",
		"outcome.correct": "正确处理",
		"outcome.cursed_sale": "诅咒出售",
		"outcome.uncontained_discard": "未收容丢弃",
		"outcome.bad_appraisal": "错误鉴定",
		"fallback.customer_note": "顾客备注",
		"fallback.customer_body": "一位顾客正在等待鉴定。",
		"fallback.risk_hint": "风险提示：未知",
		"fallback.consequence": "顾客没有评论，只把鉴定备注归档。",
		"fallback.wrong_event": "%s 在错误鉴定后扰动了店铺。",
		"item.oddity_0001.display_name": "低语茶杯",
		"item.oddity_0001.description": "一个白瓷茶杯，即使在明亮店灯下也异常冰冷。",
		"item.oddity_0001.magnifier_clue": "细裂纹在杯身周围形成淡淡的螺旋。",
		"item.oddity_0001.uv_clue": "杯沿附近隐藏的环形印记在紫外光下泛蓝。",
		"item.oddity_0001.thermometer_clue": "茶杯读数远低于室温。",
		"item.oddity_0001.wrong_event_text": "如果出售，买家会带着冻伤回来，店铺声誉受损。",
		"item.oddity_0002.display_name": "镜面硬币",
		"item.oddity_0002.description": "一枚暗淡银币，币面映出慢一秒的房间。",
		"item.oddity_0002.magnifier_clue": "细小划痕形成刻意留下的鉴定标记。",
		"item.oddity_0002.uv_clue": "隐藏的蓝色标记会在紫外光下出现。",
		"item.oddity_0002.thermometer_clue": "读数与房间温度不一致。",
		"item.oddity_0002.wrong_event_text": "店内将排入一个小型异常事件。",
		"item.oddity_0003.display_name": "灰烬八音盒",
		"item.oddity_0003.description": "一个烧焦的八音盒，盖子关闭时圆筒仍会咔嗒作响。",
		"item.oddity_0003.magnifier_clue": "细小划痕形成刻意留下的鉴定标记。",
		"item.oddity_0003.uv_clue": "隐藏的蓝色标记会在紫外光下出现。",
		"item.oddity_0003.thermometer_clue": "读数与房间温度不一致。",
		"item.oddity_0003.wrong_event_text": "店内将排入一个小型异常事件。",
		"customer.oddity_0001.title": "顾客备注：发抖的女继承人",
		"customer.oddity_0001.body": "黎明前送来一个包好的茶杯。信差拒绝第二次触碰它。",
		"customer.oddity_0001.risk_hint": "风险提示：寒意转移",
		"customer.oddity_0002.title": "顾客备注：钟表匠",
		"customer.oddity_0002.body": "一枚硬币出现在上锁的钱匣里，映出不存在的房间。",
		"customer.oddity_0002.risk_hint": "风险提示：延迟倒影",
		"customer.oddity_0003.title": "顾客备注：遗产执行人",
		"customer.oddity_0003.body": "清点遗物时，这个八音盒明明没有上弦却自己播放。",
		"customer.oddity_0003.risk_hint": "风险提示：自奏机构",
		"consequence.oddity_0001.seal": "顾客没有带走茶杯就离开了",
		"consequence.oddity_0001.sell": "买家抱怨霜痕爬满了收据",
		"consequence.oddity_0001.discard": "被丢弃的茶杯带着新冰回到门阶上。",
		"consequence.oddity_0002.seal": "钟表匠收下封印包后，不再听见延迟的回声。",
		"consequence.oddity_0002.sell": "买家匆忙付款，但门口的倒影慢了一拍。",
		"consequence.oddity_0002.discard": "铃声响过一次后，硬币又滚回柜台下。",
		"consequence.oddity_0003.seal": "遗产执行人记录说，走廊里的曲调终于停止了。",
		"consequence.oddity_0003.sell": "买家报告午夜后空婴儿房里传来音乐。",
		"consequence.oddity_0003.discard": "八音盒被安静地移走了",
		"ending.frost_sale.title": "坏结局：霜冻交易",
	},
	"zh_TW": {
		"game.title": "詛咒古物店",
		"ui.start_day": "開始一天",
		"ui.quit": "離開",
		"ui.inspect_prompt": "按 E 檢查等待鑑定的異物",
		"ui.run_status": "第 %d/%d 天 | 現金 %d | 聲望 %d",
		"ui.shop_ledger": "店鋪帳本",
		"ui.no_appraisals": "尚無鑑定紀錄。",
		"ui.ledger_entry": "第 %d 天：%s -> %s",
		"ui.result_detail_title": "鑑定結果詳情 %d/%d",
		"ui.result_detail_empty": "尚無鑑定結果詳情。",
		"ui.result_detail_body": "異物：%s\n決策：%s\n結果：%s\n現金：%+d\n聲望：%+d\n後果：%s",
		"ui.back_to_shop": "返回店鋪",
		"ui.magnifier": "放大鏡",
		"ui.uv_lamp": "紫外燈",
		"ui.thermometer": "溫度計",
		"ui.temperature": "溫度：%.1f C",
		"ui.appraisal_notes": "鑑定筆記",
		"ui.note_mag": "- 放大：%s",
		"ui.note_uv": "- UV：%s",
		"ui.note_temp": "- 溫度：%s",
		"ui.sell": "出售",
		"ui.seal": "封印",
		"ui.discard": "丟棄",
		"ui.detail_previous": "上一筆",
		"ui.detail_next": "下一筆",
		"decision.sell": "出售",
		"decision.seal": "封存",
		"decision.discard": "丟棄",
		"ui.correct_result": "正確：%s 已安全處理。",
		"ui.wrong_result": "錯誤：%s 應該%s，而不是%s。",
		"ui.cash_delta": "現金：%+d",
		"ui.reputation_delta": "聲望：%+d",
		"ui.next_day": "下一天",
		"ui.return_to_menu": "返回選單",
		"ui.run_summary": "流程總結",
		"ui.handled_count": "已處理：%d/%d 件異物",
		"ui.final_cash": "最終現金：%d",
		"ui.final_reputation": "最終聲望：%d",
		"ui.last_report": "最後紀錄：%s",
		"ui.no_consequence": "沒有紀錄後果。",
		"outcome.correct": "正確處理",
		"outcome.cursed_sale": "詛咒出售",
		"outcome.uncontained_discard": "未收容丟棄",
		"outcome.bad_appraisal": "錯誤鑑定",
		"fallback.customer_note": "顧客備註",
		"fallback.customer_body": "一位顧客正在等待鑑定。",
		"fallback.risk_hint": "風險提示：未知",
		"fallback.consequence": "顧客沒有評論，只把鑑定備註歸檔。",
		"fallback.wrong_event": "%s 在錯誤鑑定後擾動了店鋪。",
		"item.oddity_0001.display_name": "低語茶杯",
		"item.oddity_0001.description": "一只白瓷茶杯，即使在明亮店燈下也異常冰冷。",
		"item.oddity_0001.magnifier_clue": "細裂紋在杯身周圍形成淡淡的螺旋。",
		"item.oddity_0001.uv_clue": "杯沿附近隱藏的環形印記在紫外光下泛藍。",
		"item.oddity_0001.thermometer_clue": "茶杯讀數遠低於室溫。",
		"item.oddity_0001.wrong_event_text": "如果出售，買家會帶著凍傷回來，店鋪聲望受損。",
		"item.oddity_0002.display_name": "鏡面硬幣",
		"item.oddity_0002.description": "一枚暗淡銀幣，幣面映出慢一秒的房間。",
		"item.oddity_0002.magnifier_clue": "細小刮痕形成刻意留下的鑑定標記。",
		"item.oddity_0002.uv_clue": "隱藏的藍色標記會在紫外光下出現。",
		"item.oddity_0002.thermometer_clue": "讀數與房間溫度不一致。",
		"item.oddity_0002.wrong_event_text": "店內將排入一個小型異常事件。",
		"item.oddity_0003.display_name": "灰燼音樂盒",
		"item.oddity_0003.description": "一個燒焦的音樂盒，蓋子關上時圓筒仍會喀噠作響。",
		"item.oddity_0003.magnifier_clue": "細小刮痕形成刻意留下的鑑定標記。",
		"item.oddity_0003.uv_clue": "隱藏的藍色標記會在紫外光下出現。",
		"item.oddity_0003.thermometer_clue": "讀數與房間溫度不一致。",
		"item.oddity_0003.wrong_event_text": "店內將排入一個小型異常事件。",
		"customer.oddity_0001.title": "顧客備註：發抖的女繼承人",
		"customer.oddity_0001.body": "黎明前送來一只包好的茶杯。信差拒絕第二次觸碰它。",
		"customer.oddity_0001.risk_hint": "風險提示：寒意轉移",
		"customer.oddity_0002.title": "顧客備註：鐘錶匠",
		"customer.oddity_0002.body": "一枚硬幣出現在上鎖的錢匣裡，映出不存在的房間。",
		"customer.oddity_0002.risk_hint": "風險提示：延遲倒影",
		"customer.oddity_0003.title": "顧客備註：遺產執行人",
		"customer.oddity_0003.body": "清點遺物時，這個音樂盒明明沒有上弦卻自己播放。",
		"customer.oddity_0003.risk_hint": "風險提示：自奏機構",
		"consequence.oddity_0001.seal": "顧客沒有帶走茶杯就離開了",
		"consequence.oddity_0001.sell": "買家抱怨霜痕爬滿了收據",
		"consequence.oddity_0001.discard": "被丟棄的茶杯帶著新冰回到門階上。",
		"consequence.oddity_0002.seal": "鐘錶匠收下封印包後，不再聽見延遲的回聲。",
		"consequence.oddity_0002.sell": "買家匆忙付款，但門口的倒影慢了一拍。",
		"consequence.oddity_0002.discard": "鈴聲響過一次後，硬幣又滾回櫃檯下。",
		"consequence.oddity_0003.seal": "遺產執行人紀錄說，走廊裡的曲調終於停止了。",
		"consequence.oddity_0003.sell": "買家回報午夜後空嬰兒房裡傳來音樂。",
		"consequence.oddity_0003.discard": "音樂盒被安靜地移走了",
		"ending.frost_sale.title": "壞結局：霜凍交易",
	},
}

var current_locale := DEFAULT_LOCALE


func _ready() -> void:
	set_locale(DEFAULT_LOCALE)


func set_locale(locale_code: String) -> void:
	if locale_code in SUPPORTED_LOCALES:
		current_locale = locale_code
	else:
		current_locale = DEFAULT_LOCALE


func text(key: String) -> String:
	var locale_table: Dictionary = TEXT.get(current_locale, TEXT[DEFAULT_LOCALE])
	if locale_table.has(key):
		return str(locale_table[key])
	var default_table: Dictionary = TEXT[DEFAULT_LOCALE]
	return str(default_table.get(key, key))


func format_text(key: String, values: Array) -> String:
	return text(key) % values


func item_text(item_id: String, field_name: String, fallback: String = "") -> String:
	var key := "item.%s.%s" % [item_id, field_name]
	var translated := text(key)
	if translated == key:
		return fallback
	return translated
