extends Node

const DEFAULT_LOCALE := "zh_TW"
const SUPPORTED_LOCALES := ["en", "ja", "ko", "es", "pt", "ru", "zh_CN", "zh_TW"]

const TEXT := {
	"en": {
		"game.title": "Cursed Curio Shop",
		"ui.start_day": "Start Day",
		"ui.quit": "Quit",
		"ui.inspect_prompt": "Press E to inspect the waiting oddity",
		"ui.run_status": "Day %d/%d | Cash %d | Reputation %d",
		"ui.shop_ledger": "Shop Ledger",
		"ui.no_appraisals": "No appraisals filed yet.",
		"ui.ledger_entry": "Day %d: %s -> %s",
		"ui.result_detail_title": "Appraisal Detail %d/%d",
		"ui.result_detail_empty": "No appraisal detail yet.",
		"ui.result_detail_body": "Oddity: %s\nDecision: %s\nOutcome: %s\nCash: %+d\nReputation: %+d\nConsequence: %s",
		"ui.back_to_shop": "Back to Shop",
		"ui.magnifier": "Magnifier",
		"ui.uv_lamp": "UV Lamp",
		"ui.thermometer": "Thermometer",
		"ui.temperature": "Temperature: %.1f C",
		"ui.appraisal_notes": "Appraisal Notes",
		"ui.note_mag": "- Mag: %s",
		"ui.note_uv": "- UV: %s",
		"ui.note_temp": "- Temp: %s",
		"ui.sell": "Sell",
		"ui.seal": "Seal",
		"ui.discard": "Discard",
		"ui.detail_previous": "Previous",
		"ui.detail_next": "Next",
		"decision.sell": "Sell",
		"decision.seal": "Seal",
		"decision.discard": "Discard",
		"ui.correct_result": "Correct: %s is handled safely.",
		"ui.wrong_result": "Wrong: %s should be %s, not %s.",
		"ui.cash_delta": "Cash: %+d",
		"ui.reputation_delta": "Reputation: %+d",
		"ui.next_day": "Next Day",
		"ui.return_to_menu": "Return to Menu",
		"ui.run_summary": "Run Summary",
		"ui.handled_count": "Handled: %d/%d oddities",
		"ui.final_cash": "Final Cash: %d",
		"ui.final_reputation": "Final Reputation: %d",
		"ui.last_report": "Last: %s",
		"ui.no_consequence": "No consequence recorded.",
		"upgrade.ledger_desk.buy": "Upgrade Ledger Desk (-120)",
		"upgrade.ledger_desk.status_locked": "Ledger Desk: run records can be upgraded for %d cash.",
		"upgrade.ledger_desk.status_unlocked": "Ledger Desk upgraded: provenance notes added to customer briefs.",
		"upgrade.ledger_desk.provenance": "Ledger record: prior owner and circulation notes cross-checked.",
		"outcome.correct": "Correct handling",
		"outcome.cursed_sale": "Cursed sale",
		"outcome.uncontained_discard": "Uncontained discard",
		"outcome.bad_appraisal": "Bad appraisal",
		"fallback.customer_note": "Customer Note",
		"fallback.customer_body": "A customer is waiting for an appraisal.",
		"fallback.risk_hint": "Risk hint: unknown",
		"fallback.consequence": "The customer files the appraisal note without comment.",
		"fallback.wrong_event": "%s disturbs the shop after the bad appraisal.",
		"item.oddity_0001.display_name": "Whispering Teacup",
		"item.oddity_0001.description": "A white porcelain teacup that stays unnaturally cold even under bright shop lamps.",
		"item.oddity_0001.magnifier_clue": "Hairline cracks form a faint spiral around the bowl.",
		"item.oddity_0001.uv_clue": "A hidden ring-shaped mark glows blue near the rim.",
		"item.oddity_0001.thermometer_clue": "The cup reads far below room temperature.",
		"item.oddity_0001.wrong_event_text": "If sold, the buyer returns with frostbite and the shop loses reputation.",
		"item.oddity_0002.display_name": "Mirror Coin",
		"item.oddity_0002.description": "A tarnished silver coin whose face reflects a room one second out of sync.",
		"item.oddity_0002.magnifier_clue": "The stamped date repeats backward along the rim when viewed through the lens.",
		"item.oddity_0002.uv_clue": "UV light reveals a second set of initials floating above the coin face.",
		"item.oddity_0002.thermometer_clue": "The coin chills the table in a perfect circle while the air stays warm.",
		"item.oddity_0002.wrong_event_text": "If released, the coin returns in a locked till with tomorrow's receipt folded underneath.",
		"item.oddity_0003.display_name": "Ashen Music Box",
		"item.oddity_0003.description": "A scorched music box whose cylinder clicks even when the lid is shut.",
		"item.oddity_0003.magnifier_clue": "Ash is packed inside the comb teeth, but none has fallen onto the desk.",
		"item.oddity_0003.uv_clue": "UV light shows the words 'play me home' burned into the underside of the lid.",
		"item.oddity_0003.thermometer_clue": "The music box cools only while the cylinder is turning.",
		"item.oddity_0003.wrong_event_text": "If kept or sold, the tune resumes from an empty nursery after midnight.",
		"item.oddity_0004.display_name": "Cold Brass Key",
		"item.oddity_0004.description": "A brass key with cellar grime packed into the bow and a tooth pattern that never quite repeats.",
		"item.oddity_0004.magnifier_clue": "The key teeth have fresh frost only on the cuts that would enter a lock first.",
		"item.oddity_0004.uv_clue": "UV light reveals a floor-plan line etched across the bow.",
		"item.oddity_0004.thermometer_clue": "The bow is colder than the shaft, as if the handle was left outside.",
		"item.oddity_0004.wrong_event_text": "If it leaves containment, nearby locks open at 3:04 and relock from the wrong side.",
		"item.oddity_0005.display_name": "Glass Eye",
		"item.oddity_0005.description": "A polished glass prosthetic eye in a surgeon's case, unsettling but carefully catalogued.",
		"item.oddity_0005.magnifier_clue": "The maker's mark is intact and the tiny iris scratches are from medical fitting tools.",
		"item.oddity_0005.uv_clue": "UV light shows a clean serial number, not a ritual mark.",
		"item.oddity_0005.thermometer_clue": "The eye stays close to room temperature even after being handled.",
		"item.oddity_0005.wrong_event_text": "If hidden away, the legitimate buyer cancels and rumors spread that the shop destroys harmless antiques.",
		"item.oddity_0006.display_name": "Black Wax Candle",
		"item.oddity_0006.description": "A black chapel candle whose wick gives off heat without flame and smells faintly of signed names.",
		"item.oddity_0006.magnifier_clue": "Melt lines run upward toward the wick instead of down the candle.",
		"item.oddity_0006.uv_clue": "UV light reveals thumbprints circling the base like a congregation.",
		"item.oddity_0006.thermometer_clue": "The candle grows hotter after the lamp is turned away.",
		"item.oddity_0006.wrong_event_text": "If preserved or sold, the wick lights whenever a name is spoken near the shop.",
		"item.oddity_0007.display_name": "Moth-Eaten Doll",
		"item.oddity_0007.description": "A worn cloth doll shedding grey fabric dust from seams that have been repaired too many times.",
		"item.oddity_0007.magnifier_clue": "The stitched smile was resewn with thread taken from several different garments.",
		"item.oddity_0007.uv_clue": "UV light reveals small handprints pressed into the back of the dress.",
		"item.oddity_0007.thermometer_clue": "The doll is coldest around the chest seam, not the exposed fabric.",
		"item.oddity_0007.wrong_event_text": "If sent away loose, the thread spells names across a nursery wall.",
		"item.oddity_0008.display_name": "Silver Funeral Bell",
		"item.oddity_0008.description": "A tarnished silver funeral bell with a muted clapper and a ribbon faded to coffin-lining grey.",
		"item.oddity_0008.magnifier_clue": "The clapper is tied with black thread, yet the bell still vibrates under the lens.",
		"item.oddity_0008.uv_clue": "UV light reveals initials scratched inside the bell mouth.",
		"item.oddity_0008.thermometer_clue": "The bell's rim is colder than the handle despite being touched last.",
		"item.oddity_0008.wrong_event_text": "If mishandled, a funeral procession can be heard outside each locked window.",
		"item.oddity_0009.display_name": "Cracked Hand Mirror",
		"item.oddity_0009.description": "A cracked dressing-room hand mirror whose silver backing has peeled into the shape of a second face.",
		"item.oddity_0009.magnifier_clue": "The central crack splits the reflected face before it splits the glass.",
		"item.oddity_0009.uv_clue": "UV light shows no maker's mark, only a second eye where the backing has lifted.",
		"item.oddity_0009.thermometer_clue": "The mirror reaches room temperature only when its face is covered.",
		"item.oddity_0009.wrong_event_text": "If kept intact, a second reflection remains after the mirror is covered.",
		"item.oddity_0010.display_name": "Red Thread Spool",
		"item.oddity_0010.description": "A red thread spool from a matchmaker's desk, still tied to two unpaid account slips.",
		"item.oddity_0010.magnifier_clue": "Tiny knots mark paired initials rather than warnings or dates.",
		"item.oddity_0010.uv_clue": "UV light shows balanced ledger numbers written along the paper core.",
		"item.oddity_0010.thermometer_clue": "The thread is warm like recently handled cloth, but the spool core stays normal.",
		"item.oddity_0010.wrong_event_text": "If locked away or thrown out, the thread ties unrelated objects together after closing.",
		"customer.oddity_0001.title": "Customer Note: Shivering Heiress",
		"customer.oddity_0001.body": "A wrapped teacup arrived before dawn. The courier refused to touch it twice.",
		"customer.oddity_0001.risk_hint": "Risk hint: cold transfer",
		"customer.oddity_0002.title": "Customer Note: Clockmaker",
		"customer.oddity_0002.body": "A coin was found in a locked till, reflecting a room that is not there.",
		"customer.oddity_0002.risk_hint": "Risk hint: delayed reflection",
		"customer.oddity_0003.title": "Customer Note: Estate Executor",
		"customer.oddity_0003.body": "This music box played during the inventory, though no key was wound.",
		"customer.oddity_0003.risk_hint": "Risk hint: self-playing mechanism",
		"customer.oddity_0004.title": "Customer Note: Night Porter",
		"customer.oddity_0004.body": "A brass key arrived from a locked cellar door, cold enough to numb the envelope.",
		"customer.oddity_0004.risk_hint": "Risk hint: room-temperature mismatch",
		"customer.oddity_0005.title": "Customer Note: Retired Surgeon",
		"customer.oddity_0005.body": "A glass eye was found staring upward inside a sealed instrument case.",
		"customer.oddity_0005.risk_hint": "Risk hint: catalogued medical provenance, watchful surface",
		"customer.oddity_0006.title": "Customer Note: Chapel Caretaker",
		"customer.oddity_0006.body": "A black candle was found burning cold beside an unused chapel register.",
		"customer.oddity_0006.risk_hint": "Risk hint: heat rises after attention shifts",
		"customer.oddity_0007.title": "Customer Note: Boarding School Matron",
		"customer.oddity_0007.body": "A cloth doll was found in a dormitory trunk, wrapped in shed fabric scraps.",
		"customer.oddity_0007.risk_hint": "Risk hint: cold nursery trace, active stitching",
		"customer.oddity_0008.title": "Customer Note: Funeral Director",
		"customer.oddity_0008.body": "A silver bell was found inside a sealed coffin drawer that should have been empty.",
		"customer.oddity_0008.risk_hint": "Risk hint: muted clapper, active vibration",
		"customer.oddity_0009.title": "Customer Note: Theatre Widow",
		"customer.oddity_0009.body": "A cracked hand mirror was recovered from a dressing room that reflects applause after midnight.",
		"customer.oddity_0009.risk_hint": "Risk hint: split reflection, covered temperature",
		"customer.oddity_0010.title": "Customer Note: Matchmaker",
		"customer.oddity_0010.body": "A spool of red thread was found tying two account books together after closing.",
		"customer.oddity_0010.risk_hint": "Risk hint: matched accounts, warm thread",
		"consequence.oddity_0001.seal": "The customer leaves without the cup",
		"consequence.oddity_0001.sell": "The buyer complains that frost crept across the receipt",
		"consequence.oddity_0001.discard": "The discarded cup returns to the doorstep with fresh ice inside.",
		"consequence.oddity_0002.seal": "The clockmaker accepts the sealed packet and stops hearing the delayed echo.",
		"consequence.oddity_0002.sell": "The buyer pays quickly, but their reflection lags behind them at the door.",
		"consequence.oddity_0002.discard": "The coin rolls back under the counter after the bell rings once.",
		"consequence.oddity_0003.seal": "The estate executor notes that the tune finally stops in the hallway.",
		"consequence.oddity_0003.sell": "The buyer reports music from an empty nursery after midnight.",
		"consequence.oddity_0003.discard": "The music box is removed quietly",
		"consequence.oddity_0004.seal": "The porter reports that the cellar door stays shut and the key stops frosting.",
		"consequence.oddity_0004.sell": "The buyer says every lock in the house clicks open at 3:04.",
		"consequence.oddity_0004.discard": "The key returns under the shop mat with a new layer of ice.",
		"consequence.oddity_0005.seal": "The sealed case keeps tapping from the inside until the courier leaves.",
		"consequence.oddity_0005.sell": "The buyer reports that the eye stays quiet once placed in a display case.",
		"consequence.oddity_0005.discard": "The glass eye rolls back under the counter before closing time.",
		"consequence.oddity_0006.seal": "The sealed candle stains the case with warm soot before quieting.",
		"consequence.oddity_0006.sell": "The buyer says the candle lights itself whenever a name is spoken.",
		"consequence.oddity_0006.discard": "The candle collapses into harmless wax after the wick is pinched out.",
		"consequence.oddity_0007.seal": "The sealed doll stops shedding fabric after the latch is tied shut.",
		"consequence.oddity_0007.sell": "The buyer reports loose threads spelling names across a nursery wall.",
		"consequence.oddity_0007.discard": "The doll is found sitting upright in the waste bin after closing.",
		"consequence.oddity_0008.seal": "The sealed bell gives one soft ring, then stays silent in the case.",
		"consequence.oddity_0008.sell": "The buyer hears a funeral procession outside every locked window.",
		"consequence.oddity_0008.discard": "The bell rings from the rubbish crate whenever the shop goes quiet.",
		"consequence.oddity_0009.seal": "The sealed mirror fogs from the inside and keeps showing another room.",
		"consequence.oddity_0009.sell": "The buyer reports their reflection leaving the room before they do.",
		"consequence.oddity_0009.discard": "The broken mirror darkens and stops reflecting anything after disposal.",
		"consequence.oddity_0010.seal": "The sealed spool keeps tying knots around the latch from inside the case.",
		"consequence.oddity_0010.sell": "The buyer says the red thread quietly guides two lost letters together.",
		"consequence.oddity_0010.discard": "The discarded thread knots around the waste bin and will not burn.",
		"ending.frost_sale.title": "Bad Ending: Frost Sale",
	},
	"ja": {
		"game.title": "呪われた骨董店",
		"ui.start_day": "一日を始める",
		"ui.quit": "終了",
		"ui.inspect_prompt": "Eキーで待機中の奇物を鑑定",
		"ui.run_status": "%d/%d日目 | 所持金 %d | 評判 %d",
		"ui.shop_ledger": "店の台帳",
		"ui.no_appraisals": "鑑定記録はまだありません。",
		"ui.ledger_entry": "%d日目: %s -> %s",
		"ui.result_detail_title": "鑑定詳細 %d/%d",
		"ui.result_detail_empty": "鑑定詳細はまだありません。",
		"ui.result_detail_body": "奇物: %s\n判断: %s\n結果: %s\n現金: %+d\n評判: %+d\n後日談: %s",
		"ui.back_to_shop": "店に戻る",
		"ui.magnifier": "拡大鏡",
		"ui.uv_lamp": "UVランプ",
		"ui.thermometer": "温度計",
		"ui.temperature": "温度: %.1f C",
		"ui.appraisal_notes": "鑑定メモ",
		"ui.note_mag": "- 拡大: %s",
		"ui.note_uv": "- UV: %s",
		"ui.note_temp": "- 温度: %s",
		"ui.sell": "売る",
		"ui.seal": "封印",
		"ui.discard": "廃棄",
		"ui.detail_previous": "前へ",
		"ui.detail_next": "次へ",
		"decision.sell": "売却",
		"decision.seal": "封印",
		"decision.discard": "廃棄",
		"ui.correct_result": "正解: %s は安全に処理された。",
		"ui.wrong_result": "誤り: %s は %s すべきで、%s ではない。",
		"ui.cash_delta": "所持金: %+d",
		"ui.reputation_delta": "評判: %+d",
		"ui.next_day": "次の日",
		"ui.return_to_menu": "メニューへ戻る",
		"ui.run_summary": "プレイ結果",
		"ui.handled_count": "処理数: %d/%d 個",
		"ui.final_cash": "最終所持金: %d",
		"ui.final_reputation": "最終評判: %d",
		"ui.last_report": "最後: %s",
		"ui.no_consequence": "結果記録なし。",
		"outcome.correct": "正しい処理",
		"outcome.cursed_sale": "呪われた販売",
		"outcome.uncontained_discard": "未封印の廃棄",
		"outcome.bad_appraisal": "誤鑑定",
		"fallback.customer_note": "顧客メモ",
		"fallback.customer_body": "顧客が鑑定を待っている。",
		"fallback.risk_hint": "危険の手掛かり: 不明",
		"fallback.consequence": "顧客は何も言わず鑑定書をしまった。",
		"fallback.wrong_event": "%s が誤鑑定のあと店を乱す。",
		"item.oddity_0001.display_name": "囁くティーカップ",
		"item.oddity_0001.description": "明るい店内の灯りの下でも不自然に冷たい白磁のティーカップ。",
		"item.oddity_0001.magnifier_clue": "細いひびが器の周囲に淡い渦を描いている。",
		"item.oddity_0001.uv_clue": "縁の近くに隠れた輪状の印が青く光る。",
		"item.oddity_0001.thermometer_clue": "カップは室温を大きく下回っている。",
		"item.oddity_0001.wrong_event_text": "売却すると、買い手は凍傷を負って戻り、店の評判が落ちる。",
		"item.oddity_0002.display_name": "鏡映りの硬貨",
		"item.oddity_0002.description": "表面が一秒遅れの部屋を映す、くすんだ銀貨。",
		"item.oddity_0002.magnifier_clue": "細かな傷が意図的な鑑定印を形作っている。",
		"item.oddity_0002.uv_clue": "UV光の下で隠れた青い印が現れる。",
		"item.oddity_0002.thermometer_clue": "測定値が室温と一致しない。",
		"item.oddity_0002.wrong_event_text": "店内で小さな異常事象が発生する。",
		"item.oddity_0003.display_name": "灰かぶりのオルゴール",
		"item.oddity_0003.description": "蓋を閉じていてもシリンダーが鳴る、焦げたオルゴール。",
		"item.oddity_0003.magnifier_clue": "細かな傷が意図的な鑑定印を形作っている。",
		"item.oddity_0003.uv_clue": "UV光の下で隠れた青い印が現れる。",
		"item.oddity_0003.thermometer_clue": "測定値が室温と一致しない。",
		"item.oddity_0003.wrong_event_text": "店内で小さな異常事象が発生する。",
		"item.oddity_0004.display_name": "冷たい真鍮の鍵",
		"item.oddity_0004.description": "店の灯りの下でも冷えたままの真鍮の鍵。",
		"item.oddity_0004.magnifier_clue": "細い傷が意図的な鑑定印を形作っている。",
		"item.oddity_0004.uv_clue": "UV光の下で隠れた青い印が現れる。",
		"item.oddity_0004.thermometer_clue": "鍵は周囲の室温より冷たい。",
		"item.oddity_0004.wrong_event_text": "誤った鑑定の後、近くの錠がひとりでに開く。",
		"item.oddity_0005.display_name": "ガラスの義眼",
		"item.oddity_0005.description": "鑑定者を見つめ続けているような、磨かれたガラスの義眼。",
		"item.oddity_0005.magnifier_clue": "細い傷が意図的な鑑定印を形作っている。",
		"item.oddity_0005.uv_clue": "UV光の下で隠れた青い印が現れる。",
		"item.oddity_0005.thermometer_clue": "読み取り値は部屋に比べて妙に穏やかだ。",
		"item.oddity_0005.wrong_event_text": "ガラスの義眼は最後に触れた人物へ転がっていく。",
		"item.oddity_0006.display_name": "黒い蝋燭",
		"item.oddity_0006.description": "炎がないのに芯がくすぶる黒い蝋燭。",
		"item.oddity_0006.magnifier_clue": "細い傷が意図的な鑑定印を形作っている。",
		"item.oddity_0006.uv_clue": "UV光の下で隠れた青い印が現れる。",
		"item.oddity_0006.thermometer_clue": "蝋燭は周囲の部屋より高い温度を示す。",
		"item.oddity_0006.wrong_event_text": "蝋燭が最後に置かれた場所に温かい煤の跡が現れる。",
		"item.oddity_0007.display_name": "虫食いの人形",
		"item.oddity_0007.description": "古い噛み跡と冷たい埃で布が薄くなった、擦り切れた布人形。",
		"item.oddity_0007.magnifier_clue": "細い傷が意図的な鑑定印を形作っている。",
		"item.oddity_0007.uv_clue": "UV光の下で隠れた青い印が現れる。",
		"item.oddity_0007.thermometer_clue": "人形は周囲の部屋より冷たい温度を示す。",
		"item.oddity_0007.wrong_event_text": "ほつれた糸が一番近い開いた引き出しへ這っていく。",
		"item.oddity_0008.display_name": "銀の葬礼ベル",
		"item.oddity_0008.description": "触れていないのにかすかに鳴る、小さな銀の葬礼ベル。",
		"item.oddity_0008.magnifier_clue": "細い傷が意図的な鑑定印を形作っている。",
		"item.oddity_0008.uv_clue": "UV光の下で隠れた青い印が現れる。",
		"item.oddity_0008.thermometer_clue": "ベルは周囲の部屋より冷たい温度を示す。",
		"item.oddity_0008.wrong_event_text": "店の壁の向こうから遠い鐘の音が応える。",
		"item.oddity_0009.display_name": "ひび割れた手鏡",
		"item.oddity_0009.description": "映った像が一呼吸ぶん長く残る、ひび割れた手鏡。",
		"item.oddity_0009.magnifier_clue": "細い傷が意図的な鑑定印を形作っている。",
		"item.oddity_0009.uv_clue": "UV光の下で隠れた青い印が現れる。",
		"item.oddity_0009.thermometer_clue": "鏡は室温に近いが、決して一致しない。",
		"item.oddity_0009.wrong_event_text": "鏡を覆った後も、もう一つの反射が残る。",
		"item.oddity_0010.display_name": "赤い糸巻き",
		"item.oddity_0010.description": "ほどけた端が果たされていない約束へ動く赤い糸巻き。",
		"item.oddity_0010.magnifier_clue": "細い傷が意図的な鑑定印を形作っている。",
		"item.oddity_0010.uv_clue": "UV光の下で隠れた青い印が現れる。",
		"item.oddity_0010.thermometer_clue": "糸巻きは周囲の部屋より少し温かい。",
		"item.oddity_0010.wrong_event_text": "閉店後、糸が無関係な二つの物を結びつける。",
		"customer.oddity_0001.title": "顧客メモ: 震える相続人",
		"customer.oddity_0001.body": "夜明け前、包まれたティーカップが届いた。配達人は二度触るのを拒んだ。",
		"customer.oddity_0001.risk_hint": "危険の手掛かり: 冷気の移動",
		"customer.oddity_0002.title": "顧客メモ: 時計職人",
		"customer.oddity_0002.body": "鍵のかかった金庫で見つかった硬貨は、存在しない部屋を映していた。",
		"customer.oddity_0002.risk_hint": "危険の手掛かり: 遅れる反射",
		"customer.oddity_0003.title": "顧客メモ: 遺産執行人",
		"customer.oddity_0003.body": "誰もぜんまいを巻いていないのに、棚卸し中にこのオルゴールが鳴った。",
		"customer.oddity_0003.risk_hint": "危険の手掛かり: 自動演奏機構",
		"customer.oddity_0004.title": "顧客メモ：夜警",
		"customer.oddity_0004.body": "施錠された地下室の扉から真鍮の鍵が届いた。封筒まで冷たくしびれている。",
		"customer.oddity_0004.risk_hint": "危険の手がかり：室温との不一致",
		"customer.oddity_0005.title": "顧客メモ：引退した外科医",
		"customer.oddity_0005.body": "密封された器具ケースの中で、ガラスの義眼が上を向いて見つかった。",
		"customer.oddity_0005.risk_hint": "危険の手がかり：安全に再販可能、見張る物体",
		"customer.oddity_0006.title": "顧客メモ：礼拝堂の管理人",
		"customer.oddity_0006.body": "使われていない礼拝堂の記録簿のそばで、黒い蝋燭が冷たく燃えていた。",
		"customer.oddity_0006.risk_hint": "危険の手がかり：熱の不一致、再販不可",
		"customer.oddity_0007.title": "顧客メモ：寄宿学校の寮母",
		"customer.oddity_0007.body": "寄宿舎のトランクから、落ちた布切れに包まれた布人形が見つかった。",
		"customer.oddity_0007.risk_hint": "危険の手がかり：冷たい子供部屋の痕跡、封印推奨",
		"customer.oddity_0008.title": "顧客メモ：葬儀屋",
		"customer.oddity_0008.body": "空のはずの封印された棺の引き出しから、銀のベルが見つかった。",
		"customer.oddity_0008.risk_hint": "危険の手がかり：埋葬の鐘、封印推奨",
		"customer.oddity_0009.title": "顧客メモ：劇場の未亡人",
		"customer.oddity_0009.body": "深夜になると拍手を映す楽屋から、ひび割れた手鏡が回収された。",
		"customer.oddity_0009.risk_hint": "危険の手がかり：分裂する反射、廃棄推奨",
		"customer.oddity_0010.title": "顧客メモ：仲人",
		"customer.oddity_0010.body": "閉店後、二冊の帳簿を結んでいる赤い糸巻きが見つかった。",
		"customer.oddity_0010.risk_hint": "危険の手がかり：利益を生む縁、販売推奨",
		"consequence.oddity_0001.seal": "顧客はカップを持たずに帰った",
		"consequence.oddity_0001.sell": "買い手は領収書に霜が広がったと苦情を言う",
		"consequence.oddity_0001.discard": "捨てたカップが新しい氷を抱えて玄関先に戻る。",
		"consequence.oddity_0002.seal": "時計職人は封印包みを受け取り、遅れた反響を聞かなくなった。",
		"consequence.oddity_0002.sell": "買い手は急いで支払うが、戸口で反射だけが遅れている。",
		"consequence.oddity_0002.discard": "ベルが一度鳴った後、硬貨はカウンターの下へ転がり戻る。",
		"consequence.oddity_0003.seal": "遺産執行人は、廊下で曲がようやく止んだと記録した。",
		"consequence.oddity_0003.sell": "買い手は真夜中に空の子供部屋から音楽が聞こえると報告する。",
		"consequence.oddity_0003.discard": "オルゴールは静かに撤去された",
		"consequence.oddity_0004.seal": "夜警は地下室の扉が閉じたままで、鍵の霜も止まったと報告する。",
		"consequence.oddity_0004.sell": "購入者は家中の錠が3時04分に一斉に開くと言う。",
		"consequence.oddity_0004.discard": "鍵は新しい氷をまとって店のマットの下に戻る。",
		"consequence.oddity_0005.seal": "密封ケースは配達人が去るまで内側から叩き続ける。",
		"consequence.oddity_0005.sell": "購入者は、義眼を展示ケースに置くと静かになったと報告する。",
		"consequence.oddity_0005.discard": "閉店前、ガラスの義眼はカウンターの下へ転がり戻る。",
		"consequence.oddity_0006.seal": "封印された蝋燭は静まる前に、ケースを温かい煤で汚す。",
		"consequence.oddity_0006.sell": "購入者は、名前が口にされるたび蝋燭がひとりでに灯ると言う。",
		"consequence.oddity_0006.discard": "芯をつまみ消すと、蝋燭は無害な蝋へ崩れる。",
		"consequence.oddity_0007.seal": "留め金を結んで閉じると、封印された人形は布を落とさなくなる。",
		"consequence.oddity_0007.sell": "購入者は、ほつれ糸が子供部屋の壁に名前を綴ると報告する。",
		"consequence.oddity_0007.discard": "閉店後、人形はごみ箱の中でまっすぐ座って見つかる。",
		"consequence.oddity_0008.seal": "封印されたベルは柔らかく一度鳴り、その後ケースの中で沈黙する。",
		"consequence.oddity_0008.sell": "購入者は、施錠された窓の外から葬列の音が聞こえると言う。",
		"consequence.oddity_0008.discard": "店が静かになるたび、ごみ箱の中からベルが鳴る。",
		"consequence.oddity_0009.seal": "封印された鏡は内側から曇り、別の部屋を映し続ける。",
		"consequence.oddity_0009.sell": "購入者は、自分より先に反射が部屋を出ると報告する。",
		"consequence.oddity_0009.discard": "壊れた鏡は廃棄後に暗くなり、何も映さなくなる。",
		"consequence.oddity_0010.seal": "封印された糸巻きはケースの内側から留め金に結び目を作り続ける。",
		"consequence.oddity_0010.sell": "購入者は、赤い糸が二通の迷子の手紙を静かに引き合わせたと言う。",
		"consequence.oddity_0010.discard": "捨てられた糸はゴミ箱に絡まり、燃えようとしない。",
		"ending.frost_sale.title": "バッドエンド: 霜の販売",
	},
	"ko": {
		"game.title": "저주받은 골동품점",
		"ui.start_day": "하루 시작",
		"ui.quit": "종료",
		"ui.inspect_prompt": "E를 눌러 대기 중인 기물을 감정",
		"ui.run_status": "%d/%d일 | 현금 %d | 평판 %d",
		"ui.shop_ledger": "상점 장부",
		"ui.no_appraisals": "아직 감정 기록이 없습니다.",
		"ui.ledger_entry": "%d일: %s -> %s",
		"ui.result_detail_title": "감정 세부 정보 %d/%d",
		"ui.result_detail_empty": "아직 감정 세부 정보가 없습니다.",
		"ui.result_detail_body": "기물: %s\n결정: %s\n결과: %s\n현금: %+d\n평판: %+d\n후속 기록: %s",
		"ui.back_to_shop": "상점으로",
		"ui.magnifier": "돋보기",
		"ui.uv_lamp": "UV 램프",
		"ui.thermometer": "온도계",
		"ui.temperature": "온도: %.1f C",
		"ui.appraisal_notes": "감정 노트",
		"ui.note_mag": "- 확대: %s",
		"ui.note_uv": "- UV: %s",
		"ui.note_temp": "- 온도: %s",
		"ui.sell": "판매",
		"ui.seal": "봉인",
		"ui.discard": "폐기",
		"ui.detail_previous": "이전",
		"ui.detail_next": "다음",
		"decision.sell": "판매",
		"decision.seal": "봉인",
		"decision.discard": "폐기",
		"ui.correct_result": "정답: %s 이 안전하게 처리되었습니다.",
		"ui.wrong_result": "오답: %s 은 %s 해야 하며 %s 하면 안 됩니다.",
		"ui.cash_delta": "현금: %+d",
		"ui.reputation_delta": "평판: %+d",
		"ui.next_day": "다음 날",
		"ui.return_to_menu": "메뉴로",
		"ui.run_summary": "진행 요약",
		"ui.handled_count": "처리: %d/%d 개",
		"ui.final_cash": "최종 현금: %d",
		"ui.final_reputation": "최종 평판: %d",
		"ui.last_report": "마지막: %s",
		"ui.no_consequence": "기록된 결과가 없습니다.",
		"outcome.correct": "올바른 처리",
		"outcome.cursed_sale": "저주받은 판매",
		"outcome.uncontained_discard": "봉인 없는 폐기",
		"outcome.bad_appraisal": "잘못된 감정",
		"fallback.customer_note": "고객 메모",
		"fallback.customer_body": "고객이 감정을 기다리고 있습니다.",
		"fallback.risk_hint": "위험 단서: 알 수 없음",
		"fallback.consequence": "고객은 말없이 감정 기록을 보관합니다.",
		"fallback.wrong_event": "%s 이 잘못된 감정 뒤 상점을 어지럽힙니다.",
		"item.oddity_0001.display_name": "속삭이는 찻잔",
		"item.oddity_0001.description": "밝은 상점 조명 아래에서도 비정상적으로 차가운 흰 도자기 찻잔.",
		"item.oddity_0001.magnifier_clue": "가는 균열이 잔 둘레에 희미한 소용돌이를 이룹니다.",
		"item.oddity_0001.uv_clue": "가장자리 근처 숨은 고리 표식이 푸르게 빛납니다.",
		"item.oddity_0001.thermometer_clue": "찻잔은 실온보다 훨씬 낮게 측정됩니다.",
		"item.oddity_0001.wrong_event_text": "판매하면 구매자가 동상에 걸려 돌아오고 상점 평판이 떨어집니다.",
		"item.oddity_0002.display_name": "거울 동전",
		"item.oddity_0002.description": "얼굴이 1초 늦은 방을 비추는 변색된 은화.",
		"item.oddity_0002.magnifier_clue": "가는 흠집이 의도적인 감정 표식을 이룹니다.",
		"item.oddity_0002.uv_clue": "UV 빛 아래 숨은 푸른 표식이 나타납니다.",
		"item.oddity_0002.thermometer_clue": "측정값이 방 온도와 맞지 않습니다.",
		"item.oddity_0002.wrong_event_text": "상점에 작은 이상 현상이 예정됩니다.",
		"item.oddity_0003.display_name": "재 묻은 오르골",
		"item.oddity_0003.description": "뚜껑이 닫혀도 원통이 딸깍거리는 그을린 오르골.",
		"item.oddity_0003.magnifier_clue": "가는 흠집이 의도적인 감정 표식을 이룹니다.",
		"item.oddity_0003.uv_clue": "UV 빛 아래 숨은 푸른 표식이 나타납니다.",
		"item.oddity_0003.thermometer_clue": "측정값이 방 온도와 맞지 않습니다.",
		"item.oddity_0003.wrong_event_text": "상점에 작은 이상 현상이 예정됩니다.",
		"item.oddity_0004.display_name": "차가운 황동 열쇠",
		"item.oddity_0004.description": "가게 등불 아래에서도 차갑게 남아 있는 황동 열쇠.",
		"item.oddity_0004.magnifier_clue": "가느다란 흠집이 의도적인 감정 표식을 이룬다.",
		"item.oddity_0004.uv_clue": "UV 빛 아래 숨은 푸른 표식이 드러난다.",
		"item.oddity_0004.thermometer_clue": "열쇠는 주변 공기보다 낮은 온도를 보인다.",
		"item.oddity_0004.wrong_event_text": "잘못 감정한 뒤 근처 자물쇠가 혼자 열린다.",
		"item.oddity_0005.display_name": "유리 의안",
		"item.oddity_0005.description": "감정사를 계속 바라보는 듯한 광택 나는 유리 의안.",
		"item.oddity_0005.magnifier_clue": "가느다란 흠집이 의도적인 감정 표식을 이룬다.",
		"item.oddity_0005.uv_clue": "UV 빛 아래 숨은 푸른 표식이 드러난다.",
		"item.oddity_0005.thermometer_clue": "방 안에 비해 수치가 이상할 만큼 안정적이다.",
		"item.oddity_0005.wrong_event_text": "유리 의안은 마지막으로 만진 사람 쪽으로 굴러간다.",
		"item.oddity_0006.display_name": "검은 밀랍 양초",
		"item.oddity_0006.description": "불꽃 없이도 심지가 그을리는 검은 밀랍 양초.",
		"item.oddity_0006.magnifier_clue": "가느다란 흠집이 의도적인 감정 표식을 이룬다.",
		"item.oddity_0006.uv_clue": "UV 빛 아래 숨은 푸른 표식이 드러난다.",
		"item.oddity_0006.thermometer_clue": "양초는 주변 방보다 높은 온도를 보인다.",
		"item.oddity_0006.wrong_event_text": "양초가 마지막으로 놓였던 자리에 따뜻한 그을음 자국이 생긴다.",
		"item.oddity_0007.display_name": "벌레 먹은 인형",
		"item.oddity_0007.description": "오래된 물린 자국과 차가운 먼지로 천이 얇아진 낡은 천 인형.",
		"item.oddity_0007.magnifier_clue": "가느다란 흠집이 의도적인 감정 표식을 이룬다.",
		"item.oddity_0007.uv_clue": "UV 빛 아래 숨은 푸른 표식이 드러난다.",
		"item.oddity_0007.thermometer_clue": "인형은 주변 방보다 낮은 온도를 보인다.",
		"item.oddity_0007.wrong_event_text": "풀린 실이 가장 가까운 열린 서랍 쪽으로 기어간다.",
		"item.oddity_0008.display_name": "은 장례 종",
		"item.oddity_0008.description": "건드리지 않아도 희미하게 울리는 작은 은 장례 종.",
		"item.oddity_0008.magnifier_clue": "가느다란 흠집이 의도적인 감정 표식을 이룬다.",
		"item.oddity_0008.uv_clue": "UV 빛 아래 숨은 푸른 표식이 드러난다.",
		"item.oddity_0008.thermometer_clue": "종은 주변 방보다 낮은 온도를 보인다.",
		"item.oddity_0008.wrong_event_text": "가게 벽 뒤편에서 먼 종소리가 대답한다.",
		"item.oddity_0009.display_name": "금 간 손거울",
		"item.oddity_0009.description": "비친 모습이 한숨만큼 더 오래 남는 금 간 손거울.",
		"item.oddity_0009.magnifier_clue": "가느다란 흠집이 의도적인 감정 표식을 이룬다.",
		"item.oddity_0009.uv_clue": "UV 빛 아래 숨은 푸른 표식이 드러난다.",
		"item.oddity_0009.thermometer_clue": "거울은 실온에 가깝지만 절대 일치하지 않는다.",
		"item.oddity_0009.wrong_event_text": "거울을 덮은 뒤에도 두 번째 반사가 남는다.",
		"item.oddity_0010.display_name": "붉은 실타래",
		"item.oddity_0010.description": "풀린 끝이 갚지 못한 약속 쪽으로 꿈틀거리는 붉은 실타래.",
		"item.oddity_0010.magnifier_clue": "가느다란 흠집이 의도적인 감정 표식을 이룬다.",
		"item.oddity_0010.uv_clue": "UV 빛 아래 숨은 푸른 표식이 드러난다.",
		"item.oddity_0010.thermometer_clue": "실타래는 주변 방보다 따뜻하게 측정된다.",
		"item.oddity_0010.wrong_event_text": "폐점 후 실이 관련 없는 물건 둘을 묶어 둔다.",
		"customer.oddity_0001.title": "고객 메모: 떨리는 상속녀",
		"customer.oddity_0001.body": "동트기 전 포장된 찻잔이 도착했습니다. 배달원은 두 번 만지기를 거부했습니다.",
		"customer.oddity_0001.risk_hint": "위험 단서: 냉기 전이",
		"customer.oddity_0002.title": "고객 메모: 시계공",
		"customer.oddity_0002.body": "잠긴 금고에서 발견된 동전은 존재하지 않는 방을 비추고 있었습니다.",
		"customer.oddity_0002.risk_hint": "위험 단서: 지연된 반사",
		"customer.oddity_0003.title": "고객 메모: 유산 집행인",
		"customer.oddity_0003.body": "태엽을 감지 않았는데도 재고 조사 중 이 오르골이 연주되었습니다.",
		"customer.oddity_0003.risk_hint": "위험 단서: 자동 연주 장치",
		"customer.oddity_0004.title": "고객 메모: 야간 문지기",
		"customer.oddity_0004.body": "잠긴 지하실 문에서 온 황동 열쇠가 봉투까지 얼얼하게 만들 만큼 차갑다.",
		"customer.oddity_0004.risk_hint": "위험 단서: 실온 불일치",
		"customer.oddity_0005.title": "고객 메모: 은퇴한 외과의",
		"customer.oddity_0005.body": "밀봉된 수술 도구 상자 안에서 유리 의안이 위를 응시한 채 발견되었다.",
		"customer.oddity_0005.risk_hint": "위험 단서: 안전한 재판매, 지켜보는 물건",
		"customer.oddity_0006.title": "고객 메모: 예배당 관리인",
		"customer.oddity_0006.body": "사용하지 않는 예배당 명부 옆에서 검은 양초가 차갑게 타고 있었다.",
		"customer.oddity_0006.risk_hint": "위험 단서: 열 불일치, 재판매 위험",
		"customer.oddity_0007.title": "고객 메모: 기숙 학교 사감",
		"customer.oddity_0007.body": "기숙사 트렁크 안에서 떨어진 천 조각에 싸인 천 인형이 발견되었다.",
		"customer.oddity_0007.risk_hint": "위험 단서: 차가운 아이 방 흔적, 봉인 권장",
		"customer.oddity_0008.title": "고객 메모: 장례지도사",
		"customer.oddity_0008.body": "비어 있어야 할 봉인된 관 서랍 안에서 은 종이 발견되었다.",
		"customer.oddity_0008.risk_hint": "위험 단서: 매장 종소리, 봉인 권장",
		"customer.oddity_0009.title": "고객 메모: 극장 미망인",
		"customer.oddity_0009.body": "자정 뒤 박수 소리를 비추는 분장실에서 금 간 손거울이 회수되었다.",
		"customer.oddity_0009.risk_hint": "위험 단서: 갈라진 반사, 폐기 권장",
		"customer.oddity_0010.title": "고객 메모: 중매인",
		"customer.oddity_0010.body": "폐점 후 붉은 실타래가 장부 두 권을 묶고 있는 것이 발견되었다.",
		"customer.oddity_0010.risk_hint": "위험 단서: 이익이 되는 인연, 판매 권장",
		"consequence.oddity_0001.seal": "고객은 찻잔 없이 떠납니다",
		"consequence.oddity_0001.sell": "구매자가 영수증에 서리가 번졌다고 항의합니다",
		"consequence.oddity_0001.discard": "버린 찻잔이 새 얼음을 담고 문 앞에 돌아옵니다.",
		"consequence.oddity_0002.seal": "시계공은 봉인된 꾸러미를 받고 지연된 메아리를 더 듣지 않습니다.",
		"consequence.oddity_0002.sell": "구매자는 급히 돈을 내지만 문가에서 반사만 뒤처집니다.",
		"consequence.oddity_0002.discard": "종이 한 번 울린 뒤 동전은 카운터 밑으로 굴러 돌아옵니다.",
		"consequence.oddity_0003.seal": "유산 집행인은 복도에서 마침내 음악이 멈췄다고 기록합니다.",
		"consequence.oddity_0003.sell": "구매자는 자정 이후 빈 아이 방에서 음악이 들린다고 보고합니다.",
		"consequence.oddity_0003.discard": "오르골은 조용히 치워졌습니다",
		"consequence.oddity_0004.seal": "문지기는 지하실 문이 닫힌 채 유지되고 열쇠의 서리도 멈췄다고 전한다.",
		"consequence.oddity_0004.sell": "구매자는 새벽 3시 4분마다 집 안의 모든 자물쇠가 열린다고 말한다.",
		"consequence.oddity_0004.discard": "열쇠는 새 얼음을 두른 채 가게 매트 아래로 돌아온다.",
		"consequence.oddity_0005.seal": "밀봉 상자는 배달원이 떠날 때까지 안쪽에서 계속 두드린다.",
		"consequence.oddity_0005.sell": "구매자는 의안을 진열장에 넣자 조용해졌다고 보고한다.",
		"consequence.oddity_0005.discard": "폐점 전 유리 의안은 다시 계산대 아래로 굴러 들어간다.",
		"consequence.oddity_0006.seal": "봉인된 양초는 조용해지기 전 케이스에 따뜻한 그을음을 남긴다.",
		"consequence.oddity_0006.sell": "구매자는 이름이 불릴 때마다 양초가 저절로 켜진다고 말한다.",
		"consequence.oddity_0006.discard": "심지를 눌러 끄자 양초는 해 없는 밀랍으로 무너진다.",
		"consequence.oddity_0007.seal": "걸쇠를 묶어 닫자 봉인된 인형은 더 이상 천 조각을 흘리지 않는다.",
		"consequence.oddity_0007.sell": "구매자는 풀린 실이 아이 방 벽에 이름을 쓴다고 보고한다.",
		"consequence.oddity_0007.discard": "폐점 후 인형은 쓰레기통 안에 똑바로 앉아 있는 채 발견된다.",
		"consequence.oddity_0008.seal": "봉인된 종은 한 번 부드럽게 울린 뒤 케이스 안에서 조용해진다.",
		"consequence.oddity_0008.sell": "구매자는 잠긴 창문마다 바깥에서 장례 행렬 소리가 들린다고 말한다.",
		"consequence.oddity_0008.discard": "가게가 조용해질 때마다 쓰레기 상자 안에서 종이 울린다.",
		"consequence.oddity_0009.seal": "봉인된 거울은 안쪽에서 김이 서리고 다른 방을 계속 비춘다.",
		"consequence.oddity_0009.sell": "구매자는 자신의 반사가 자신보다 먼저 방을 나간다고 보고한다.",
		"consequence.oddity_0009.discard": "깨진 거울은 폐기 후 어두워지고 아무것도 비추지 않는다.",
		"consequence.oddity_0010.seal": "봉인된 실타래는 케이스 안쪽에서 걸쇠 주위에 매듭을 계속 만든다.",
		"consequence.oddity_0010.sell": "구매자는 붉은 실이 잃어버린 편지 두 통을 조용히 만나게 했다고 말한다.",
		"consequence.oddity_0010.discard": "버려진 실은 쓰레기통에 매듭져 감기고 타지 않는다.",
		"ending.frost_sale.title": "나쁜 결말: 서리 판매",
	},
	"es": {
		"game.title": "Tienda de Curios Malditos",
		"ui.start_day": "Comenzar dia",
		"ui.quit": "Salir",
		"ui.inspect_prompt": "Pulsa E para inspeccionar la rareza en espera",
		"ui.run_status": "Dia %d/%d | Dinero %d | Reputacion %d",
		"ui.shop_ledger": "Libro de la tienda",
		"ui.no_appraisals": "Aun no hay tasaciones archivadas.",
		"ui.ledger_entry": "Dia %d: %s -> %s",
		"ui.result_detail_title": "Detalle de tasacion %d/%d",
		"ui.result_detail_empty": "Aun no hay detalle de tasacion.",
		"ui.result_detail_body": "Rareza: %s\nDecision: %s\nResultado: %s\nEfectivo: %+d\nReputacion: %+d\nConsecuencia: %s",
		"ui.back_to_shop": "Volver a la tienda",
		"ui.magnifier": "Lupa",
		"ui.uv_lamp": "Lampara UV",
		"ui.thermometer": "Termometro",
		"ui.temperature": "Temperatura: %.1f C",
		"ui.appraisal_notes": "Notas de tasacion",
		"ui.note_mag": "- Lupa: %s",
		"ui.note_uv": "- UV: %s",
		"ui.note_temp": "- Temp: %s",
		"ui.sell": "Vender",
		"ui.seal": "Sellar",
		"ui.discard": "Desechar",
		"ui.detail_previous": "Anterior",
		"ui.detail_next": "Siguiente",
		"decision.sell": "Vender",
		"decision.seal": "Sellar",
		"decision.discard": "Desechar",
		"ui.correct_result": "Correcto: %s se manejo con seguridad.",
		"ui.wrong_result": "Error: %s debia ser %s, no %s.",
		"ui.cash_delta": "Dinero: %+d",
		"ui.reputation_delta": "Reputacion: %+d",
		"ui.next_day": "Dia siguiente",
		"ui.return_to_menu": "Volver al menu",
		"ui.run_summary": "Resumen",
		"ui.handled_count": "Tratadas: %d/%d rarezas",
		"ui.final_cash": "Dinero final: %d",
		"ui.final_reputation": "Reputacion final: %d",
		"ui.last_report": "Ultimo: %s",
		"ui.no_consequence": "No hay consecuencia registrada.",
		"outcome.correct": "Manejo correcto",
		"outcome.cursed_sale": "Venta maldita",
		"outcome.uncontained_discard": "Desecho sin contener",
		"outcome.bad_appraisal": "Mala tasacion",
		"fallback.customer_note": "Nota del cliente",
		"fallback.customer_body": "Un cliente espera una tasacion.",
		"fallback.risk_hint": "Pista de riesgo: desconocida",
		"fallback.consequence": "El cliente archiva la nota sin comentario.",
		"fallback.wrong_event": "%s perturba la tienda tras la mala tasacion.",
		"item.oddity_0001.display_name": "Taza susurrante",
		"item.oddity_0001.description": "Una taza de porcelana blanca que permanece anormalmente fria incluso bajo las lamparas de la tienda.",
		"item.oddity_0001.magnifier_clue": "Grietas finas forman una espiral tenue alrededor del cuenco.",
		"item.oddity_0001.uv_clue": "Una marca circular oculta brilla azul cerca del borde.",
		"item.oddity_0001.thermometer_clue": "La taza marca muy por debajo de la temperatura ambiente.",
		"item.oddity_0001.wrong_event_text": "Si se vende, el comprador vuelve con congelacion y la tienda pierde reputacion.",
		"item.oddity_0002.display_name": "Moneda espejo",
		"item.oddity_0002.description": "Una moneda de plata opaca cuyo rostro refleja una habitacion con un segundo de retraso.",
		"item.oddity_0002.magnifier_clue": "Rayas finas forman una marca de tasacion deliberada.",
		"item.oddity_0002.uv_clue": "Una marca azul oculta aparece bajo luz UV.",
		"item.oddity_0002.thermometer_clue": "La lectura no coincide con la habitacion.",
		"item.oddity_0002.wrong_event_text": "Un evento anomalo menor queda preparado para la tienda.",
		"item.oddity_0003.display_name": "Caja musical cenicienta",
		"item.oddity_0003.description": "Una caja musical quemada cuyo cilindro hace clic incluso con la tapa cerrada.",
		"item.oddity_0003.magnifier_clue": "Rayas finas forman una marca de tasacion deliberada.",
		"item.oddity_0003.uv_clue": "Una marca azul oculta aparece bajo luz UV.",
		"item.oddity_0003.thermometer_clue": "La lectura no coincide con la habitacion.",
		"item.oddity_0003.wrong_event_text": "Un evento anomalo menor queda preparado para la tienda.",
		"item.oddity_0004.display_name": "Llave de bronce fria",
		"item.oddity_0004.description": "Una llave de bronce que sigue fria incluso bajo la lampara de la tienda.",
		"item.oddity_0004.magnifier_clue": "Rasguños finos forman una marca de tasacion deliberada.",
		"item.oddity_0004.uv_clue": "Una marca azul oculta aparece bajo luz UV.",
		"item.oddity_0004.thermometer_clue": "La llave mide mas frio que la habitacion.",
		"item.oddity_0004.wrong_event_text": "Una cerradura cercana se abre tras la mala tasacion.",
		"item.oddity_0005.display_name": "Ojo de vidrio",
		"item.oddity_0005.description": "Un ojo de vidrio pulido que parece seguir mirando al tasador.",
		"item.oddity_0005.magnifier_clue": "Rasguños finos forman una marca de tasacion deliberada.",
		"item.oddity_0005.uv_clue": "Una marca azul oculta aparece bajo luz UV.",
		"item.oddity_0005.thermometer_clue": "La lectura esta extranamente estable frente a la habitacion.",
		"item.oddity_0005.wrong_event_text": "El ojo de vidrio rueda hacia la ultima persona que lo toco.",
		"item.oddity_0006.display_name": "Vela de cera negra",
		"item.oddity_0006.description": "Una vela de cera negra cuya mecha humea sin llama.",
		"item.oddity_0006.magnifier_clue": "Rasguños finos forman una marca de tasacion deliberada.",
		"item.oddity_0006.uv_clue": "Una marca azul oculta aparece bajo luz UV.",
		"item.oddity_0006.thermometer_clue": "La vela mide mas calor que la habitacion.",
		"item.oddity_0006.wrong_event_text": "Aparece una marca tibia de hollin donde se dejo la vela por ultima vez.",
		"item.oddity_0007.display_name": "Muneca apolillada",
		"item.oddity_0007.description": "Una muneca de tela gastada, adelgazada por mordidas viejas y polvo frio.",
		"item.oddity_0007.magnifier_clue": "Rasguños finos forman una marca de tasacion deliberada.",
		"item.oddity_0007.uv_clue": "Una marca azul oculta aparece bajo luz UV.",
		"item.oddity_0007.thermometer_clue": "La muneca mide mas frio que la habitacion.",
		"item.oddity_0007.wrong_event_text": "Hilos sueltos avanzan hacia el cajon abierto mas cercano.",
		"item.oddity_0008.display_name": "Campana funeraria de plata",
		"item.oddity_0008.description": "Una pequena campana funeraria de plata que suena debilmente incluso sin tocarla.",
		"item.oddity_0008.magnifier_clue": "Rasguños finos forman una marca de tasacion deliberada.",
		"item.oddity_0008.uv_clue": "Una marca azul oculta aparece bajo luz UV.",
		"item.oddity_0008.thermometer_clue": "La campana mide mas frio que la habitacion.",
		"item.oddity_0008.wrong_event_text": "Un repique lejano responde desde detras de la pared de la tienda.",
		"item.oddity_0009.display_name": "Espejo de mano agrietado",
		"item.oddity_0009.description": "Un espejo de mano agrietado cuyo reflejo permanece un aliento de mas.",
		"item.oddity_0009.magnifier_clue": "Rasguños finos forman una marca de tasacion deliberada.",
		"item.oddity_0009.uv_clue": "Una marca azul oculta aparece bajo luz UV.",
		"item.oddity_0009.thermometer_clue": "El espejo se acerca a la temperatura de la habitacion, pero nunca coincide.",
		"item.oddity_0009.wrong_event_text": "Un segundo reflejo permanece despues de cubrir el espejo.",
		"item.oddity_0010.display_name": "Carrete de hilo rojo",
		"item.oddity_0010.description": "Un carrete de hilo rojo cuyo cabo suelto tiembla hacia promesas sin pagar.",
		"item.oddity_0010.magnifier_clue": "Rasguños finos forman una marca de tasacion deliberada.",
		"item.oddity_0010.uv_clue": "Una marca azul oculta aparece bajo luz UV.",
		"item.oddity_0010.thermometer_clue": "El carrete marca mas calor que la habitacion.",
		"item.oddity_0010.wrong_event_text": "El hilo ata dos objetos sin relacion despues del cierre.",
		"customer.oddity_0001.title": "Nota del cliente: heredera temblorosa",
		"customer.oddity_0001.body": "Una taza envuelta llego antes del amanecer. El mensajero se nego a tocarla dos veces.",
		"customer.oddity_0001.risk_hint": "Pista de riesgo: transferencia fria",
		"customer.oddity_0002.title": "Nota del cliente: relojero",
		"customer.oddity_0002.body": "La moneda aparecio en una caja cerrada y refleja una habitacion que no existe.",
		"customer.oddity_0002.risk_hint": "Pista de riesgo: reflejo retrasado",
		"customer.oddity_0003.title": "Nota del cliente: albacea",
		"customer.oddity_0003.body": "La caja musical sono durante el inventario aunque nadie le dio cuerda.",
		"customer.oddity_0003.risk_hint": "Pista de riesgo: mecanismo automatico",
		"customer.oddity_0004.title": "Nota del cliente: portero nocturno",
		"customer.oddity_0004.body": "Una llave de bronce llego desde una puerta de bodega cerrada, tan fria que entumecio el sobre.",
		"customer.oddity_0004.risk_hint": "Pista de riesgo: desajuste de temperatura",
		"customer.oddity_0005.title": "Nota del cliente: cirujano retirado",
		"customer.oddity_0005.body": "Un ojo de vidrio fue hallado mirando hacia arriba dentro de un estuche de instrumentos sellado.",
		"customer.oddity_0005.risk_hint": "Pista de riesgo: reventa segura, objeto vigilante",
		"customer.oddity_0006.title": "Nota del cliente: cuidador de capilla",
		"customer.oddity_0006.body": "Una vela negra fue hallada ardiendo fria junto a un registro de capilla sin usar.",
		"customer.oddity_0006.risk_hint": "Pista de riesgo: desajuste de calor, reventa insegura",
		"customer.oddity_0007.title": "Nota del cliente: matrona del internado",
		"customer.oddity_0007.body": "Una muneca de tela fue hallada en un baul de dormitorio, envuelta en retazos desprendidos.",
		"customer.oddity_0007.risk_hint": "Pista de riesgo: rastro frio de dormitorio infantil, contencion recomendada",
		"customer.oddity_0008.title": "Nota del cliente: director funerario",
		"customer.oddity_0008.body": "Una campana de plata fue hallada dentro de un cajon de ataud sellado que debia estar vacio.",
		"customer.oddity_0008.risk_hint": "Pista de riesgo: campanada funeraria, contencion recomendada",
		"customer.oddity_0009.title": "Nota del cliente: viuda del teatro",
		"customer.oddity_0009.body": "Un espejo de mano agrietado fue recuperado de un camerino que refleja aplausos despues de medianoche.",
		"customer.oddity_0009.risk_hint": "Pista de riesgo: reflejo dividido, descarte recomendado",
		"customer.oddity_0010.title": "Nota del cliente: casamentera",
		"customer.oddity_0010.body": "Un carrete de hilo rojo fue hallado atando dos libros de cuentas tras el cierre.",
		"customer.oddity_0010.risk_hint": "Pista de riesgo: vinculo rentable, venta recomendada",
		"consequence.oddity_0001.seal": "El cliente se marcha sin la taza",
		"consequence.oddity_0001.sell": "El comprador se queja de que la escarcha cubrio el recibo",
		"consequence.oddity_0001.discard": "La taza desechada vuelve al umbral con hielo nuevo dentro.",
		"consequence.oddity_0002.seal": "El relojero acepta el paquete sellado y deja de oir el eco retrasado.",
		"consequence.oddity_0002.sell": "El comprador paga rapido, pero su reflejo se retrasa en la puerta.",
		"consequence.oddity_0002.discard": "La moneda rueda de vuelta bajo el mostrador tras una campanada.",
		"consequence.oddity_0003.seal": "El albacea anota que la melodia por fin se detiene en el pasillo.",
		"consequence.oddity_0003.sell": "El comprador informa de musica en una guarderia vacia despues de medianoche.",
		"consequence.oddity_0003.discard": "La caja musical se retira en silencio",
		"consequence.oddity_0004.seal": "El portero informa que la puerta del sotano queda cerrada y la llave deja de escarcharse.",
		"consequence.oddity_0004.sell": "El comprador dice que todas las cerraduras de la casa se abren a las 3:04.",
		"consequence.oddity_0004.discard": "La llave vuelve bajo el felpudo de la tienda con una nueva capa de hielo.",
		"consequence.oddity_0005.seal": "El estuche sellado sigue golpeando desde dentro hasta que se marcha el mensajero.",
		"consequence.oddity_0005.sell": "El comprador informa que el ojo queda quieto al colocarlo en una vitrina.",
		"consequence.oddity_0005.discard": "El ojo de vidrio rueda de vuelta bajo el mostrador antes del cierre.",
		"consequence.oddity_0006.seal": "La vela sellada mancha el estuche con hollin tibio antes de calmarse.",
		"consequence.oddity_0006.sell": "El comprador dice que la vela se enciende sola cada vez que se pronuncia un nombre.",
		"consequence.oddity_0006.discard": "La vela se derrumba en cera inocua cuando se apaga la mecha.",
		"consequence.oddity_0007.seal": "La muneca sellada deja de soltar tela cuando el cierre queda atado.",
		"consequence.oddity_0007.sell": "El comprador informa que hilos sueltos escriben nombres en la pared de un cuarto infantil.",
		"consequence.oddity_0007.discard": "La muneca aparece sentada derecha en el cubo de basura tras el cierre.",
		"consequence.oddity_0008.seal": "La campana sellada da un toque suave y luego queda silenciosa en el estuche.",
		"consequence.oddity_0008.sell": "El comprador oye una procesion funeraria fuera de cada ventana cerrada.",
		"consequence.oddity_0008.discard": "La campana suena desde el cajon de basura cada vez que la tienda queda en silencio.",
		"consequence.oddity_0009.seal": "El espejo sellado se empaña por dentro y sigue mostrando otra habitacion.",
		"consequence.oddity_0009.sell": "El comprador informa que su reflejo sale de la habitacion antes que el.",
		"consequence.oddity_0009.discard": "El espejo roto se oscurece y deja de reflejar cualquier cosa tras desecharlo.",
		"consequence.oddity_0010.seal": "El carrete sellado sigue haciendo nudos alrededor del cierre desde dentro del estuche.",
		"consequence.oddity_0010.sell": "El comprador dice que el hilo rojo guia en silencio dos cartas perdidas.",
		"consequence.oddity_0010.discard": "El hilo desechado se anuda alrededor del cubo y no arde.",
		"ending.frost_sale.title": "Final malo: venta helada",
	},
	"pt": {
		"game.title": "Loja de Curiosidades Amaldicoadas",
		"ui.start_day": "Iniciar dia",
		"ui.quit": "Sair",
		"ui.inspect_prompt": "Pressione E para inspecionar a curiosidade em espera",
		"ui.run_status": "Dia %d/%d | Dinheiro %d | Reputacao %d",
		"ui.shop_ledger": "Livro da loja",
		"ui.no_appraisals": "Nenhuma avaliacao arquivada ainda.",
		"ui.ledger_entry": "Dia %d: %s -> %s",
		"ui.result_detail_title": "Detalhe da avaliacao %d/%d",
		"ui.result_detail_empty": "Ainda nao ha detalhe de avaliacao.",
		"ui.result_detail_body": "Curio: %s\nDecisao: %s\nResultado: %s\nDinheiro: %+d\nReputacao: %+d\nConsequencia: %s",
		"ui.back_to_shop": "Voltar a loja",
		"ui.magnifier": "Lupa",
		"ui.uv_lamp": "Lampada UV",
		"ui.thermometer": "Termometro",
		"ui.temperature": "Temperatura: %.1f C",
		"ui.appraisal_notes": "Notas de avaliacao",
		"ui.note_mag": "- Lupa: %s",
		"ui.note_uv": "- UV: %s",
		"ui.note_temp": "- Temp: %s",
		"ui.sell": "Vender",
		"ui.seal": "Selar",
		"ui.discard": "Descartar",
		"ui.detail_previous": "Anterior",
		"ui.detail_next": "Proximo",
		"decision.sell": "Vender",
		"decision.seal": "Selar",
		"decision.discard": "Descartar",
		"ui.correct_result": "Correto: %s foi tratado com seguranca.",
		"ui.wrong_result": "Errado: %s deveria ser %s, nao %s.",
		"ui.cash_delta": "Dinheiro: %+d",
		"ui.reputation_delta": "Reputacao: %+d",
		"ui.next_day": "Proximo dia",
		"ui.return_to_menu": "Voltar ao menu",
		"ui.run_summary": "Resumo",
		"ui.handled_count": "Tratadas: %d/%d curiosidades",
		"ui.final_cash": "Dinheiro final: %d",
		"ui.final_reputation": "Reputacao final: %d",
		"ui.last_report": "Ultimo: %s",
		"ui.no_consequence": "Nenhuma consequencia registrada.",
		"outcome.correct": "Tratamento correto",
		"outcome.cursed_sale": "Venda amaldicoada",
		"outcome.uncontained_discard": "Descarte sem conter",
		"outcome.bad_appraisal": "Avaliacao ruim",
		"fallback.customer_note": "Nota do cliente",
		"fallback.customer_body": "Um cliente aguarda uma avaliacao.",
		"fallback.risk_hint": "Pista de risco: desconhecida",
		"fallback.consequence": "O cliente arquiva a nota sem comentario.",
		"fallback.wrong_event": "%s perturba a loja apos a avaliacao ruim.",
		"item.oddity_0001.display_name": "Xicara sussurrante",
		"item.oddity_0001.description": "Uma xicara de porcelana branca que permanece anormalmente fria mesmo sob as lampadas da loja.",
		"item.oddity_0001.magnifier_clue": "Rachaduras finas formam uma espiral fraca ao redor da tigela.",
		"item.oddity_0001.uv_clue": "Uma marca circular oculta brilha em azul perto da borda.",
		"item.oddity_0001.thermometer_clue": "A xicara marca muito abaixo da temperatura ambiente.",
		"item.oddity_0001.wrong_event_text": "Se vendida, o comprador volta com queimadura de frio e a loja perde reputacao.",
		"item.oddity_0002.display_name": "Moeda espelhada",
		"item.oddity_0002.description": "Uma moeda de prata escurecida cujo rosto reflete uma sala com um segundo de atraso.",
		"item.oddity_0002.magnifier_clue": "Riscos finos formam uma marca de avaliacao deliberada.",
		"item.oddity_0002.uv_clue": "Uma marca azul oculta aparece sob luz UV.",
		"item.oddity_0002.thermometer_clue": "A leitura nao combina com a sala.",
		"item.oddity_0002.wrong_event_text": "Um pequeno evento anomalo fica preparado para a loja.",
		"item.oddity_0003.display_name": "Caixa de musica cinzenta",
		"item.oddity_0003.description": "Uma caixa de musica chamuscada cujo cilindro estala mesmo com a tampa fechada.",
		"item.oddity_0003.magnifier_clue": "Riscos finos formam uma marca de avaliacao deliberada.",
		"item.oddity_0003.uv_clue": "Uma marca azul oculta aparece sob luz UV.",
		"item.oddity_0003.thermometer_clue": "A leitura nao combina com a sala.",
		"item.oddity_0003.wrong_event_text": "Um pequeno evento anomalo fica preparado para a loja.",
		"item.oddity_0004.display_name": "Chave de latao fria",
		"item.oddity_0004.description": "Uma chave de latao que continua fria mesmo sob a lampada da loja.",
		"item.oddity_0004.magnifier_clue": "Riscos finos formam uma marca de avaliacao deliberada.",
		"item.oddity_0004.uv_clue": "Uma marca azul escondida aparece sob luz UV.",
		"item.oddity_0004.thermometer_clue": "A chave marca mais frio que o ambiente.",
		"item.oddity_0004.wrong_event_text": "Uma fechadura proxima se abre depois da avaliacao errada.",
		"item.oddity_0005.display_name": "Olho de vidro",
		"item.oddity_0005.description": "Um olho de vidro polido que parece continuar observando o avaliador.",
		"item.oddity_0005.magnifier_clue": "Riscos finos formam uma marca de avaliacao deliberada.",
		"item.oddity_0005.uv_clue": "Uma marca azul escondida aparece sob luz UV.",
		"item.oddity_0005.thermometer_clue": "A leitura fica estranhamente calma em relacao ao ambiente.",
		"item.oddity_0005.wrong_event_text": "O olho de vidro rola na direcao da ultima pessoa que o tocou.",
		"item.oddity_0006.display_name": "Vela de cera preta",
		"item.oddity_0006.description": "Uma vela de cera preta cujo pavio fumega sem chama.",
		"item.oddity_0006.magnifier_clue": "Riscos finos formam uma marca de avaliacao deliberada.",
		"item.oddity_0006.uv_clue": "Uma marca azul escondida aparece sob luz UV.",
		"item.oddity_0006.thermometer_clue": "A vela marca mais calor que o ambiente.",
		"item.oddity_0006.wrong_event_text": "Uma marca morna de fuligem aparece onde a vela foi deixada por ultimo.",
		"item.oddity_0007.display_name": "Boneca roida",
		"item.oddity_0007.description": "Uma boneca de pano gasta, afinada por mordidas antigas e poeira fria.",
		"item.oddity_0007.magnifier_clue": "Riscos finos formam uma marca de avaliacao deliberada.",
		"item.oddity_0007.uv_clue": "Uma marca azul escondida aparece sob luz UV.",
		"item.oddity_0007.thermometer_clue": "A boneca marca mais frio que o ambiente.",
		"item.oddity_0007.wrong_event_text": "Fios soltos rastejam ate a gaveta aberta mais proxima.",
		"item.oddity_0008.display_name": "Sino funerario de prata",
		"item.oddity_0008.description": "Um pequeno sino funerario de prata que soa fraco mesmo sem ser tocado.",
		"item.oddity_0008.magnifier_clue": "Riscos finos formam uma marca de avaliacao deliberada.",
		"item.oddity_0008.uv_clue": "Uma marca azul escondida aparece sob luz UV.",
		"item.oddity_0008.thermometer_clue": "O sino marca mais frio que o ambiente.",
		"item.oddity_0008.wrong_event_text": "Um toque distante responde por tras da parede da loja.",
		"item.oddity_0009.display_name": "Espelho de mao rachado",
		"item.oddity_0009.description": "Um espelho de mao rachado cujo reflexo permanece um sopro a mais.",
		"item.oddity_0009.magnifier_clue": "Riscos finos formam uma marca de avaliacao deliberada.",
		"item.oddity_0009.uv_clue": "Uma marca azul escondida aparece sob luz UV.",
		"item.oddity_0009.thermometer_clue": "O espelho fica perto da temperatura ambiente, mas nunca igual.",
		"item.oddity_0009.wrong_event_text": "Um segundo reflexo permanece depois que o espelho e coberto.",
		"item.oddity_0010.display_name": "Carretel de linha vermelha",
		"item.oddity_0010.description": "Um carretel de linha vermelha cuja ponta solta treme rumo a promessas nao pagas.",
		"item.oddity_0010.magnifier_clue": "Riscos finos formam uma marca de avaliacao deliberada.",
		"item.oddity_0010.uv_clue": "Uma marca azul escondida aparece sob luz UV.",
		"item.oddity_0010.thermometer_clue": "O carretel marca mais calor que a sala.",
		"item.oddity_0010.wrong_event_text": "A linha amarra dois objetos sem relacao depois do fechamento.",
		"customer.oddity_0001.title": "Nota do cliente: herdeira tremula",
		"customer.oddity_0001.body": "Uma xicara embrulhada chegou antes do amanhecer. O entregador se recusou a toca-la duas vezes.",
		"customer.oddity_0001.risk_hint": "Pista de risco: transferencia fria",
		"customer.oddity_0002.title": "Nota do cliente: relojoeiro",
		"customer.oddity_0002.body": "Uma moeda foi encontrada em uma caixa trancada, refletindo uma sala que nao existe.",
		"customer.oddity_0002.risk_hint": "Pista de risco: reflexo atrasado",
		"customer.oddity_0003.title": "Nota do cliente: executor do espolio",
		"customer.oddity_0003.body": "Esta caixa de musica tocou durante o inventario, embora ninguem a tenha dado corda.",
		"customer.oddity_0003.risk_hint": "Pista de risco: mecanismo automatico",
		"customer.oddity_0004.title": "Nota do cliente: porteiro noturno",
		"customer.oddity_0004.body": "Uma chave de latao veio de uma porta de porao trancada, fria o bastante para gelar o envelope.",
		"customer.oddity_0004.risk_hint": "Dica de risco: temperatura incoerente",
		"customer.oddity_0005.title": "Nota do cliente: cirurgiao aposentado",
		"customer.oddity_0005.body": "Um olho de vidro foi encontrado olhando para cima dentro de um estojo de instrumentos selado.",
		"customer.oddity_0005.risk_hint": "Dica de risco: revenda segura, objeto vigilante",
		"customer.oddity_0006.title": "Nota do cliente: zelador da capela",
		"customer.oddity_0006.body": "Uma vela preta foi encontrada queimando fria ao lado de um livro de capela sem uso.",
		"customer.oddity_0006.risk_hint": "Dica de risco: calor incoerente, revenda insegura",
		"customer.oddity_0007.title": "Nota do cliente: inspetora do internato",
		"customer.oddity_0007.body": "Uma boneca de pano foi encontrada em um bau de dormitorio, envolta em retalhos soltos.",
		"customer.oddity_0007.risk_hint": "Dica de risco: rastro frio de quarto infantil, contencao recomendada",
		"customer.oddity_0008.title": "Nota do cliente: agente funerario",
		"customer.oddity_0008.body": "Um sino de prata foi encontrado dentro de uma gaveta de caixao selada que deveria estar vazia.",
		"customer.oddity_0008.risk_hint": "Dica de risco: badalada funeraria, contencao recomendada",
		"customer.oddity_0009.title": "Nota do cliente: viuva do teatro",
		"customer.oddity_0009.body": "Um espelho de mao rachado foi recuperado de um camarim que reflete aplausos depois da meia-noite.",
		"customer.oddity_0009.risk_hint": "Dica de risco: reflexo dividido, descarte recomendado",
		"customer.oddity_0010.title": "Nota do cliente: casamenteira",
		"customer.oddity_0010.body": "Um carretel de linha vermelha foi encontrado amarrando dois livros-caixa depois do fechamento.",
		"customer.oddity_0010.risk_hint": "Dica de risco: vinculo lucrativo, venda recomendada",
		"consequence.oddity_0001.seal": "O cliente vai embora sem a xicara",
		"consequence.oddity_0001.sell": "O comprador reclama que a geada cobriu o recibo",
		"consequence.oddity_0001.discard": "A xicara descartada volta ao degrau com gelo novo dentro.",
		"consequence.oddity_0002.seal": "O relojoeiro aceita o pacote selado e para de ouvir o eco atrasado.",
		"consequence.oddity_0002.sell": "O comprador paga rapido, mas seu reflexo se atrasa na porta.",
		"consequence.oddity_0002.discard": "A moeda rola de volta para baixo do balcao depois de um toque.",
		"consequence.oddity_0003.seal": "O executor anota que a melodia finalmente para no corredor.",
		"consequence.oddity_0003.sell": "O comprador relata musica em um quarto infantil vazio depois da meia-noite.",
		"consequence.oddity_0003.discard": "A caixa de musica e removida em silencio",
		"consequence.oddity_0004.seal": "O porteiro relata que a porta do porao permanece fechada e a chave para de criar gelo.",
		"consequence.oddity_0004.sell": "O comprador diz que toda fechadura da casa se abre as 3:04.",
		"consequence.oddity_0004.discard": "A chave volta sob o tapete da loja com uma nova camada de gelo.",
		"consequence.oddity_0005.seal": "O estojo selado continua batendo por dentro ate o mensageiro ir embora.",
		"consequence.oddity_0005.sell": "O comprador relata que o olho fica quieto quando colocado numa vitrine.",
		"consequence.oddity_0005.discard": "O olho de vidro rola de volta para baixo do balcao antes do fechamento.",
		"consequence.oddity_0006.seal": "A vela selada mancha o estojo com fuligem morna antes de aquietar.",
		"consequence.oddity_0006.sell": "O comprador diz que a vela se acende sozinha sempre que um nome e dito.",
		"consequence.oddity_0006.discard": "A vela desaba em cera inofensiva depois que o pavio e apagado.",
		"consequence.oddity_0007.seal": "A boneca selada para de soltar tecido depois que a trava e amarrada.",
		"consequence.oddity_0007.sell": "O comprador relata fios soltos escrevendo nomes na parede de um quarto infantil.",
		"consequence.oddity_0007.discard": "A boneca e encontrada sentada ereta na lixeira depois do fechamento.",
		"consequence.oddity_0008.seal": "O sino selado toca uma vez suavemente e entao fica quieto no estojo.",
		"consequence.oddity_0008.sell": "O comprador ouve um cortejo funebre do lado de fora de cada janela trancada.",
		"consequence.oddity_0008.discard": "O sino toca dentro da caixa de lixo sempre que a loja fica silenciosa.",
		"consequence.oddity_0009.seal": "O espelho selado embaca por dentro e continua mostrando outro quarto.",
		"consequence.oddity_0009.sell": "O comprador relata que seu reflexo sai do quarto antes dele.",
		"consequence.oddity_0009.discard": "O espelho quebrado escurece e deixa de refletir qualquer coisa depois do descarte.",
		"consequence.oddity_0010.seal": "O carretel selado continua dando nos ao redor do fecho pelo lado de dentro da caixa.",
		"consequence.oddity_0010.sell": "O comprador diz que a linha vermelha guia em silencio duas cartas perdidas.",
		"consequence.oddity_0010.discard": "A linha descartada da nos ao redor da lixeira e nao queima.",
		"ending.frost_sale.title": "Final ruim: venda congelada",
	},
	"ru": {
		"game.title": "Лавка проклятых редкостей",
		"ui.start_day": "Начать день",
		"ui.quit": "Выйти",
		"ui.inspect_prompt": "Нажмите E, чтобы осмотреть ожидающий предмет",
		"ui.run_status": "День %d/%d | Деньги %d | Репутация %d",
		"ui.shop_ledger": "Журнал лавки",
		"ui.no_appraisals": "Оценок пока нет.",
		"ui.ledger_entry": "День %d: %s -> %s",
		"ui.result_detail_title": "Детали оценки %d/%d",
		"ui.result_detail_empty": "Деталей оценки пока нет.",
		"ui.result_detail_body": "Диковина: %s\nРешение: %s\nИтог: %s\nДеньги: %+d\nРепутация: %+d\nПоследствие: %s",
		"ui.back_to_shop": "Вернуться в лавку",
		"ui.magnifier": "Лупа",
		"ui.uv_lamp": "УФ-лампа",
		"ui.thermometer": "Термометр",
		"ui.temperature": "Температура: %.1f C",
		"ui.appraisal_notes": "Заметки оценки",
		"ui.note_mag": "- Лупа: %s",
		"ui.note_uv": "- УФ: %s",
		"ui.note_temp": "- Темп.: %s",
		"ui.sell": "Продать",
		"ui.seal": "Запечатать",
		"ui.discard": "Выбросить",
		"ui.detail_previous": "Назад",
		"ui.detail_next": "Далее",
		"decision.sell": "Продать",
		"decision.seal": "Запечатать",
		"decision.discard": "Выбросить",
		"ui.correct_result": "Верно: %s обработан безопасно.",
		"ui.wrong_result": "Ошибка: %s нужно было %s, а не %s.",
		"ui.cash_delta": "Деньги: %+d",
		"ui.reputation_delta": "Репутация: %+d",
		"ui.next_day": "Следующий день",
		"ui.return_to_menu": "В меню",
		"ui.run_summary": "Итог забега",
		"ui.handled_count": "Обработано: %d/%d предметов",
		"ui.final_cash": "Итоговые деньги: %d",
		"ui.final_reputation": "Итоговая репутация: %d",
		"ui.last_report": "Последнее: %s",
		"ui.no_consequence": "Последствий не записано.",
		"outcome.correct": "Верная обработка",
		"outcome.cursed_sale": "Проклятая продажа",
		"outcome.uncontained_discard": "Выброшено без удержания",
		"outcome.bad_appraisal": "Плохая оценка",
		"fallback.customer_note": "Записка клиента",
		"fallback.customer_body": "Клиент ждет оценки.",
		"fallback.risk_hint": "Подсказка риска: неизвестно",
		"fallback.consequence": "Клиент молча подшивает оценку.",
		"fallback.wrong_event": "%s тревожит лавку после плохой оценки.",
		"item.oddity_0001.display_name": "Шепчущая чашка",
		"item.oddity_0001.description": "Белая фарфоровая чашка остается неестественно холодной даже под яркими лампами лавки.",
		"item.oddity_0001.magnifier_clue": "Тонкие трещины образуют слабую спираль вокруг чаши.",
		"item.oddity_0001.uv_clue": "Скрытая кольцевая метка у края светится синим под УФ.",
		"item.oddity_0001.thermometer_clue": "Чашка показывает температуру намного ниже комнатной.",
		"item.oddity_0001.wrong_event_text": "Если продать ее, покупатель вернется с обморожением, а репутация лавки упадет.",
		"item.oddity_0002.display_name": "Зеркальная монета",
		"item.oddity_0002.description": "Потускневшая серебряная монета отражает комнату с задержкой в одну секунду.",
		"item.oddity_0002.magnifier_clue": "Тонкие царапины образуют намеренную оценочную метку.",
		"item.oddity_0002.uv_clue": "Под УФ-светом проявляется скрытая синяя метка.",
		"item.oddity_0002.thermometer_clue": "Показания не совпадают с температурой комнаты.",
		"item.oddity_0002.wrong_event_text": "В лавке готовится небольшая аномалия.",
		"item.oddity_0003.display_name": "Пепельная музыкальная шкатулка",
		"item.oddity_0003.description": "Обгоревшая музыкальная шкатулка щелкает цилиндром даже с закрытой крышкой.",
		"item.oddity_0003.magnifier_clue": "Тонкие царапины образуют намеренную оценочную метку.",
		"item.oddity_0003.uv_clue": "Под УФ-светом проявляется скрытая синяя метка.",
		"item.oddity_0003.thermometer_clue": "Показания не совпадают с температурой комнаты.",
		"item.oddity_0003.wrong_event_text": "В лавке готовится небольшая аномалия.",
		"item.oddity_0004.display_name": "Холодный латунный ключ",
		"item.oddity_0004.description": "Латунный ключ остается холодным даже под лампой лавки.",
		"item.oddity_0004.magnifier_clue": "Тонкие царапины складываются в намеренную оценочную метку.",
		"item.oddity_0004.uv_clue": "Под УФ-светом проявляется скрытая синяя метка.",
		"item.oddity_0004.thermometer_clue": "Ключ холоднее воздуха в комнате.",
		"item.oddity_0004.wrong_event_text": "После ошибочной оценки ближайший замок щелкает и открывается.",
		"item.oddity_0005.display_name": "Стеклянный глаз",
		"item.oddity_0005.description": "Отполированный стеклянный глаз будто продолжает следить за оценщиком.",
		"item.oddity_0005.magnifier_clue": "Тонкие царапины складываются в намеренную оценочную метку.",
		"item.oddity_0005.uv_clue": "Под УФ-светом проявляется скрытая синяя метка.",
		"item.oddity_0005.thermometer_clue": "Показание странно спокойно по сравнению с комнатой.",
		"item.oddity_0005.wrong_event_text": "Стеклянный глаз катится к тому, кто коснулся его последним.",
		"item.oddity_0006.display_name": "Черная восковая свеча",
		"item.oddity_0006.description": "Черная восковая свеча, фитиль которой тлеет без пламени.",
		"item.oddity_0006.magnifier_clue": "Тонкие царапины складываются в намеренную оценочную метку.",
		"item.oddity_0006.uv_clue": "Под УФ-светом проявляется скрытая синяя метка.",
		"item.oddity_0006.thermometer_clue": "Свеча теплее комнаты вокруг нее.",
		"item.oddity_0006.wrong_event_text": "Теплый след сажи появляется там, где свечу ставили в последний раз.",
		"item.oddity_0007.display_name": "Изъеденная кукла",
		"item.oddity_0007.description": "Потрепанная тряпичная кукла с тканью, истонченной старыми укусами и холодной пылью.",
		"item.oddity_0007.magnifier_clue": "Тонкие царапины складываются в намеренную оценочную метку.",
		"item.oddity_0007.uv_clue": "Под УФ-светом проявляется скрытая синяя метка.",
		"item.oddity_0007.thermometer_clue": "Кукла холоднее комнаты вокруг нее.",
		"item.oddity_0007.wrong_event_text": "Свободные нити ползут к ближайшему открытому ящику.",
		"item.oddity_0008.display_name": "Серебряный погребальный колокольчик",
		"item.oddity_0008.description": "Маленький серебряный погребальный колокольчик слабо звенит даже без прикосновения.",
		"item.oddity_0008.magnifier_clue": "Тонкие царапины складываются в намеренную оценочную метку.",
		"item.oddity_0008.uv_clue": "Под УФ-светом проявляется скрытая синяя метка.",
		"item.oddity_0008.thermometer_clue": "Колокольчик холоднее комнаты вокруг него.",
		"item.oddity_0008.wrong_event_text": "Далекий звон отвечает из-за стены лавки.",
		"item.oddity_0009.display_name": "Треснувшее ручное зеркало",
		"item.oddity_0009.description": "Треснувшее ручное зеркало, отражение в котором задерживается на лишний вдох.",
		"item.oddity_0009.magnifier_clue": "Тонкие царапины складываются в намеренную оценочную метку.",
		"item.oddity_0009.uv_clue": "Под УФ-светом проявляется скрытая синяя метка.",
		"item.oddity_0009.thermometer_clue": "Зеркало почти равно комнатной температуре, но никогда не совпадает.",
		"item.oddity_0009.wrong_event_text": "После того как зеркало накрывают, второе отражение остается.",
		"item.oddity_0010.display_name": "Катушка красной нити",
		"item.oddity_0010.description": "Катушка красной нити, свободный конец которой тянется к неоплаченным обещаниям.",
		"item.oddity_0010.magnifier_clue": "Тонкие царапины складываются в намеренную оценочную метку.",
		"item.oddity_0010.uv_clue": "Под УФ-светом проявляется скрытая синяя метка.",
		"item.oddity_0010.thermometer_clue": "Катушка теплее комнаты вокруг нее.",
		"item.oddity_0010.wrong_event_text": "После закрытия нить связывает два несвязанных предмета.",
		"customer.oddity_0001.title": "Записка клиента: дрожащая наследница",
		"customer.oddity_0001.body": "Завернутая чашка прибыла до рассвета. Курьер отказался коснуться ее второй раз.",
		"customer.oddity_0001.risk_hint": "Подсказка риска: перенос холода",
		"customer.oddity_0002.title": "Записка клиента: часовщик",
		"customer.oddity_0002.body": "Монету нашли в запертом ящике; она отражает комнату, которой нет.",
		"customer.oddity_0002.risk_hint": "Подсказка риска: запаздывающее отражение",
		"customer.oddity_0003.title": "Записка клиента: душеприказчик",
		"customer.oddity_0003.body": "Эта шкатулка заиграла во время описи, хотя ключ никто не заводил.",
		"customer.oddity_0003.risk_hint": "Подсказка риска: самоиграющий механизм",
		"customer.oddity_0004.title": "Записка клиента: ночной сторож",
		"customer.oddity_0004.body": "Латунный ключ прибыл от запертой двери подвала, холодный настолько, что онемел конверт.",
		"customer.oddity_0004.risk_hint": "Подсказка риска: несоответствие температуре комнаты",
		"customer.oddity_0005.title": "Записка клиента: хирург на пенсии",
		"customer.oddity_0005.body": "Стеклянный глаз нашли смотрящим вверх внутри запечатанного футляра с инструментами.",
		"customer.oddity_0005.risk_hint": "Подсказка риска: безопасная перепродажа, наблюдающий предмет",
		"customer.oddity_0006.title": "Записка клиента: смотритель часовни",
		"customer.oddity_0006.body": "Черную свечу нашли холодно горящей рядом с неиспользованной книгой часовни.",
		"customer.oddity_0006.risk_hint": "Подсказка риска: несоответствие тепла, опасная перепродажа",
		"customer.oddity_0007.title": "Записка клиента: надзирательница пансиона",
		"customer.oddity_0007.body": "Тряпичную куклу нашли в сундуке общежития, завернутой в осыпавшиеся лоскуты.",
		"customer.oddity_0007.risk_hint": "Подсказка риска: холодный след детской, нужна изоляция",
		"customer.oddity_0008.title": "Записка клиента: распорядитель похорон",
		"customer.oddity_0008.body": "Серебряный колокольчик нашли в запечатанном ящике гроба, который должен был быть пустым.",
		"customer.oddity_0008.risk_hint": "Подсказка риска: погребальный звон, нужна изоляция",
		"customer.oddity_0009.title": "Записка клиента: театральная вдова",
		"customer.oddity_0009.body": "Треснувшее ручное зеркало нашли в гримерке, где после полуночи отражаются аплодисменты.",
		"customer.oddity_0009.risk_hint": "Подсказка риска: раздвоенное отражение, нужна утилизация",
		"customer.oddity_0010.title": "Записка клиента: сваха",
		"customer.oddity_0010.body": "Катушку красной нити нашли после закрытия: она связывала две учетные книги.",
		"customer.oddity_0010.risk_hint": "Подсказка риска: выгодная связь, нужна продажа",
		"consequence.oddity_0001.seal": "Клиент уходит без чашки",
		"consequence.oddity_0001.sell": "Покупатель жалуется, что иней расползся по чеку",
		"consequence.oddity_0001.discard": "Выброшенная чашка возвращается к порогу с новым льдом внутри.",
		"consequence.oddity_0002.seal": "Часовщик принимает запечатанный пакет и больше не слышит запоздалое эхо.",
		"consequence.oddity_0002.sell": "Покупатель быстро платит, но его отражение отстает у двери.",
		"consequence.oddity_0002.discard": "После одного звонка монета выкатывается обратно под прилавок.",
		"consequence.oddity_0003.seal": "Душеприказчик отмечает, что мелодия в коридоре наконец стихла.",
		"consequence.oddity_0003.sell": "Покупатель сообщает о музыке из пустой детской после полуночи.",
		"consequence.oddity_0003.discard": "Шкатулку тихо убирают",
		"consequence.oddity_0004.seal": "Сторож сообщает, что дверь подвала остается закрытой, а ключ перестал покрываться инеем.",
		"consequence.oddity_0004.sell": "Покупатель говорит, что каждый замок в доме открывается в 3:04.",
		"consequence.oddity_0004.discard": "Ключ возвращается под коврик лавки с новым слоем льда.",
		"consequence.oddity_0005.seal": "Запечатанный футляр стучит изнутри, пока курьер не уходит.",
		"consequence.oddity_0005.sell": "Покупатель сообщает, что глаз затих, когда его положили в витрину.",
		"consequence.oddity_0005.discard": "Перед закрытием стеклянный глаз снова закатывается под прилавок.",
		"consequence.oddity_0006.seal": "Запечатанная свеча пачкает футляр теплой сажей, прежде чем стихнуть.",
		"consequence.oddity_0006.sell": "Покупатель говорит, что свеча загорается сама, когда произносят имя.",
		"consequence.oddity_0006.discard": "Когда фитиль гасят пальцами, свеча распадается на безвредный воск.",
		"consequence.oddity_0007.seal": "Запечатанная кукла перестает осыпать ткань после того, как защелку перевязывают.",
		"consequence.oddity_0007.sell": "Покупатель сообщает, что свободные нити пишут имена на стене детской.",
		"consequence.oddity_0007.discard": "После закрытия куклу находят сидящей прямо в мусорной корзине.",
		"consequence.oddity_0008.seal": "Запечатанный колокольчик тихо звенит один раз, затем умолкает в футляре.",
		"consequence.oddity_0008.sell": "Покупатель слышит похоронную процессию за каждым запертым окном.",
		"consequence.oddity_0008.discard": "Колокольчик звенит из мусорного ящика всякий раз, когда лавка стихает.",
		"consequence.oddity_0009.seal": "Запечатанное зеркало запотевает изнутри и продолжает показывать другую комнату.",
		"consequence.oddity_0009.sell": "Покупатель сообщает, что его отражение выходит из комнаты раньше него.",
		"consequence.oddity_0009.discard": "Разбитое зеркало темнеет и перестает что-либо отражать после утилизации.",
		"consequence.oddity_0010.seal": "Запечатанная катушка изнутри завязывает узлы вокруг защелки футляра.",
		"consequence.oddity_0010.sell": "Покупатель говорит, что красная нить тихо свела два потерянных письма.",
		"consequence.oddity_0010.discard": "Выброшенная нить обвивает мусорную корзину узлами и не горит.",
		"ending.frost_sale.title": "Плохая концовка: морозная продажа",
	},
	"zh_CN": {
		"game.title": "诅咒古物店",
		"ui.start_day": "开始一天",
		"ui.quit": "退出",
		"ui.inspect_prompt": "按 E 检查等待鉴定的异物",
		"ui.run_status": "第 %d/%d 天 | 现金 %d | 声誉 %d",
		"ui.shop_ledger": "店铺账本",
		"ui.no_appraisals": "尚无鉴定记录。",
		"ui.ledger_entry": "第 %d 天：%s -> %s",
		"ui.result_detail_title": "鉴定结果详情 %d/%d",
		"ui.result_detail_empty": "尚无鉴定结果详情。",
		"ui.result_detail_body": "异物：%s\n决策：%s\n结果：%s\n现金：%+d\n声望：%+d\n后果：%s",
		"ui.back_to_shop": "返回店铺",
		"ui.magnifier": "放大镜",
		"ui.uv_lamp": "紫外灯",
		"ui.thermometer": "温度计",
		"ui.temperature": "温度：%.1f C",
		"ui.appraisal_notes": "鉴定笔记",
		"ui.note_mag": "- 放大：%s",
		"ui.note_uv": "- UV：%s",
		"ui.note_temp": "- 温度：%s",
		"ui.sell": "出售",
		"ui.seal": "封印",
		"ui.discard": "丢弃",
		"ui.detail_previous": "上一笔",
		"ui.detail_next": "下一笔",
		"decision.sell": "出售",
		"decision.seal": "封存",
		"decision.discard": "丢弃",
		"ui.correct_result": "正确：%s 已安全处理。",
		"ui.wrong_result": "错误：%s 应该%s，而不是%s。",
		"ui.cash_delta": "现金：%+d",
		"ui.reputation_delta": "声誉：%+d",
		"ui.next_day": "下一天",
		"ui.return_to_menu": "返回菜单",
		"ui.run_summary": "流程总结",
		"ui.handled_count": "已处理：%d/%d 件异物",
		"ui.final_cash": "最终现金：%d",
		"ui.final_reputation": "最终声誉：%d",
		"ui.last_report": "最后记录：%s",
		"ui.no_consequence": "没有记录后果。",
		"outcome.correct": "正确处理",
		"outcome.cursed_sale": "诅咒出售",
		"outcome.uncontained_discard": "未收容丢弃",
		"outcome.bad_appraisal": "错误鉴定",
		"fallback.customer_note": "顾客备注",
		"fallback.customer_body": "一位顾客正在等待鉴定。",
		"fallback.risk_hint": "风险提示：未知",
		"fallback.consequence": "顾客没有评论，只把鉴定备注归档。",
		"fallback.wrong_event": "%s 在错误鉴定后扰动了店铺。",
		"item.oddity_0001.display_name": "低语茶杯",
		"item.oddity_0001.description": "一个白瓷茶杯，即使在明亮店灯下也异常冰冷。",
		"item.oddity_0001.magnifier_clue": "细裂纹在杯身周围形成淡淡的螺旋。",
		"item.oddity_0001.uv_clue": "杯沿附近隐藏的环形印记在紫外光下泛蓝。",
		"item.oddity_0001.thermometer_clue": "茶杯读数远低于室温。",
		"item.oddity_0001.wrong_event_text": "如果出售，买家会带着冻伤回来，店铺声誉受损。",
		"item.oddity_0002.display_name": "镜面硬币",
		"item.oddity_0002.description": "一枚暗淡银币，币面映出慢一秒的房间。",
		"item.oddity_0002.magnifier_clue": "细小划痕形成刻意留下的鉴定标记。",
		"item.oddity_0002.uv_clue": "隐藏的蓝色标记会在紫外光下出现。",
		"item.oddity_0002.thermometer_clue": "读数与房间温度不一致。",
		"item.oddity_0002.wrong_event_text": "店内将排入一个小型异常事件。",
		"item.oddity_0003.display_name": "灰烬八音盒",
		"item.oddity_0003.description": "一个烧焦的八音盒，盖子关闭时圆筒仍会咔嗒作响。",
		"item.oddity_0003.magnifier_clue": "细小划痕形成刻意留下的鉴定标记。",
		"item.oddity_0003.uv_clue": "隐藏的蓝色标记会在紫外光下出现。",
		"item.oddity_0003.thermometer_clue": "读数与房间温度不一致。",
		"item.oddity_0003.wrong_event_text": "店内将排入一个小型异常事件。",
		"item.oddity_0004.display_name": "冰冷黄铜钥匙",
		"item.oddity_0004.description": "一把黄铜钥匙，即使放在店灯下仍然冰冷。",
		"item.oddity_0004.magnifier_clue": "细小刮痕组成刻意留下的鉴定标记。",
		"item.oddity_0004.uv_clue": "UV 光下会浮现隐藏的蓝色标记。",
		"item.oddity_0004.thermometer_clue": "钥匙温度低于周围室温。",
		"item.oddity_0004.wrong_event_text": "错误鉴定后，附近的锁会自行弹开。",
		"item.oddity_0005.display_name": "玻璃义眼",
		"item.oddity_0005.description": "一颗抛光玻璃义眼，像是一直盯着鉴定者。",
		"item.oddity_0005.magnifier_clue": "细小刮痕组成刻意留下的鉴定标记。",
		"item.oddity_0005.uv_clue": "UV 光下会浮现隐藏的蓝色标记。",
		"item.oddity_0005.thermometer_clue": "读数比周围环境异常平稳。",
		"item.oddity_0005.wrong_event_text": "玻璃义眼会滚向最后碰过它的人。",
		"item.oddity_0006.display_name": "黑蜡烛",
		"item.oddity_0006.description": "一支黑蜡烛，没有火焰时烛芯仍像在闷烧。",
		"item.oddity_0006.magnifier_clue": "细小刮痕组成刻意留下的鉴定标记。",
		"item.oddity_0006.uv_clue": "UV 光下会浮现隐藏的蓝色标记。",
		"item.oddity_0006.thermometer_clue": "蜡烛温度高于周围室温。",
		"item.oddity_0006.wrong_event_text": "黑蜡烛最后放置的位置会留下温热煤痕。",
		"item.oddity_0007.display_name": "虫蛀布偶",
		"item.oddity_0007.description": "一个磨损的布偶，布料被旧咬痕和冷灰尘侵蚀得很薄。",
		"item.oddity_0007.magnifier_clue": "细小刮痕组成刻意留下的鉴定标记。",
		"item.oddity_0007.uv_clue": "UV 光下会浮现隐藏的蓝色标记。",
		"item.oddity_0007.thermometer_clue": "布偶温度低于周围室温。",
		"item.oddity_0007.wrong_event_text": "松开的线头会朝最近打开的抽屉爬去。",
		"item.oddity_0008.display_name": "银制丧铃",
		"item.oddity_0008.description": "一只小银制丧铃，即使无人触碰也会微弱作响。",
		"item.oddity_0008.magnifier_clue": "细小刮痕组成刻意留下的鉴定标记。",
		"item.oddity_0008.uv_clue": "UV 光下会浮现隐藏的蓝色标记。",
		"item.oddity_0008.thermometer_clue": "铃温度低于周围室温。",
		"item.oddity_0008.wrong_event_text": "店墙后方会传来远处铃声回应。",
		"item.oddity_0009.display_name": "裂纹手镜",
		"item.oddity_0009.description": "一面有裂纹的手镜，倒影会多停留一口气。",
		"item.oddity_0009.magnifier_clue": "细小刮痕组成刻意留下的鉴定标记。",
		"item.oddity_0009.uv_clue": "UV 光下会浮现隐藏的蓝色标记。",
		"item.oddity_0009.thermometer_clue": "镜子接近室温，却从不完全一致。",
		"item.oddity_0009.wrong_event_text": "镜子被盖住后，第二个倒影仍会留下。",
		"item.oddity_0010.display_name": "红线轴",
		"item.oddity_0010.description": "一卷红线轴，松开的线端会朝未偿的承诺微微抽动。",
		"item.oddity_0010.magnifier_clue": "细小刮痕组成刻意留下的鉴定标记。",
		"item.oddity_0010.uv_clue": "UV 光下会浮现隐藏的蓝色标记。",
		"item.oddity_0010.thermometer_clue": "线轴比周围房间更暖。",
		"item.oddity_0010.wrong_event_text": "打烊后，红线会把两个无关物件绑在一起。",
		"customer.oddity_0001.title": "顾客备注：发抖的女继承人",
		"customer.oddity_0001.body": "黎明前送来一个包好的茶杯。信差拒绝第二次触碰它。",
		"customer.oddity_0001.risk_hint": "风险提示：寒意转移",
		"customer.oddity_0002.title": "顾客备注：钟表匠",
		"customer.oddity_0002.body": "一枚硬币出现在上锁的钱匣里，映出不存在的房间。",
		"customer.oddity_0002.risk_hint": "风险提示：延迟倒影",
		"customer.oddity_0003.title": "顾客备注：遗产执行人",
		"customer.oddity_0003.body": "清点遗物时，这个八音盒明明没有上弦却自己播放。",
		"customer.oddity_0003.risk_hint": "风险提示：自奏机构",
		"customer.oddity_0004.title": "顾客备注：夜班门房",
		"customer.oddity_0004.body": "一把黄铜钥匙来自上锁的地窖门，冷到连信封都发麻。",
		"customer.oddity_0004.risk_hint": "风险提示：与室温不符",
		"customer.oddity_0005.title": "顾客备注：退休外科医师",
		"customer.oddity_0005.body": "一颗玻璃义眼在密封器械盒中被发现，正朝上凝视。",
		"customer.oddity_0005.risk_hint": "风险提示：可安全转售，但物件持续注视",
		"customer.oddity_0006.title": "顾客备注：礼拜堂看管人",
		"customer.oddity_0006.body": "一支黑蜡烛在未使用的礼拜堂登记册旁被发现，像是冷冷燃烧着。",
		"customer.oddity_0006.risk_hint": "风险提示：热度异常，不宜转售",
		"customer.oddity_0007.title": "顾客备注：寄宿学校女舍监",
		"customer.oddity_0007.body": "一个布偶在宿舍箱子里被发现，外面裹着脱落的布料碎片。",
		"customer.oddity_0007.risk_hint": "风险提示：冰冷儿童房痕迹，建议封存",
		"customer.oddity_0008.title": "顾客备注：殡仪馆主管",
		"customer.oddity_0008.body": "一只银铃在密封棺木抽屉内被发现，那里本应是空的。",
		"customer.oddity_0008.risk_hint": "风险提示：葬礼铃声，建议封存",
		"customer.oddity_0009.title": "顾客备注：剧院遗孀",
		"customer.oddity_0009.body": "一面裂纹手镜来自午夜后会映出掌声的化妆间。",
		"customer.oddity_0009.risk_hint": "风险提示：分裂倒影，建议丢弃",
		"customer.oddity_0010.title": "顾客备注：媒人",
		"customer.oddity_0010.body": "打烊后，有人发现一卷红线轴把两本账簿绑在一起。",
		"customer.oddity_0010.risk_hint": "风险提示：有利连结，建议出售",
		"consequence.oddity_0001.seal": "顾客没有带走茶杯就离开了",
		"consequence.oddity_0001.sell": "买家抱怨霜痕爬满了收据",
		"consequence.oddity_0001.discard": "被丢弃的茶杯带着新冰回到门阶上。",
		"consequence.oddity_0002.seal": "钟表匠收下封印包后，不再听见延迟的回声。",
		"consequence.oddity_0002.sell": "买家匆忙付款，但门口的倒影慢了一拍。",
		"consequence.oddity_0002.discard": "铃声响过一次后，硬币又滚回柜台下。",
		"consequence.oddity_0003.seal": "遗产执行人记录说，走廊里的曲调终于停止了。",
		"consequence.oddity_0003.sell": "买家报告午夜后空婴儿房里传来音乐。",
		"consequence.oddity_0003.discard": "八音盒被安静地移走了",
		"consequence.oddity_0004.seal": "门房回报地窖门保持关闭，钥匙也停止结霜。",
		"consequence.oddity_0004.sell": "买家说屋内所有锁都会在 3:04 自行弹开。",
		"consequence.oddity_0004.discard": "钥匙带着新冰层回到店门垫下。",
		"consequence.oddity_0005.seal": "封存盒在快递离开前一直从内侧轻敲。",
		"consequence.oddity_0005.sell": "买家回报，义眼被放进展示盒后就安静下来。",
		"consequence.oddity_0005.discard": "打烊前，玻璃义眼又滚回柜台下方。",
		"consequence.oddity_0006.seal": "封存蜡烛安静前，先在盒内留下温热煤痕。",
		"consequence.oddity_0006.sell": "买家说每当有人说出名字，蜡烛就会自行点燃。",
		"consequence.oddity_0006.discard": "烛芯被掐灭后，蜡烛塌成无害蜡块。",
		"consequence.oddity_0007.seal": "封存盒扣紧后，布偶不再掉落布料。",
		"consequence.oddity_0007.sell": "买家回报，松开的线头会在儿童房墙上拼出名字。",
		"consequence.oddity_0007.discard": "打烊后，布偶被发现直坐在垃圾桶里。",
		"consequence.oddity_0008.seal": "封存铃轻轻响了一声，随后在盒中安静下来。",
		"consequence.oddity_0008.sell": "买家听见每扇上锁窗外都有葬礼队伍经过。",
		"consequence.oddity_0008.discard": "每当店里安静下来，垃圾箱里的铃就会响起。",
		"consequence.oddity_0009.seal": "封存镜从内侧起雾，并持续映出另一个房间。",
		"consequence.oddity_0009.sell": "买家回报，自己的倒影会比本人更早离开房间。",
		"consequence.oddity_0009.discard": "破镜在丢弃后变暗，再也不映出任何东西。",
		"consequence.oddity_0010.seal": "封存的线轴不断从盒内在锁扣周围打结。",
		"consequence.oddity_0010.sell": "买家说红线安静地把两封遗失的信牵到一起。",
		"consequence.oddity_0010.discard": "被丢弃的红线缠住垃圾桶并拒绝燃烧。",
		"ending.frost_sale.title": "坏结局：霜冻交易",
	},
	"zh_TW": {
		"game.title": "詛咒古物店",
		"ui.start_day": "開始一天",
		"ui.quit": "離開",
		"ui.inspect_prompt": "按 E 檢查等待鑑定的異物",
		"ui.run_status": "第 %d/%d 天 | 現金 %d | 聲望 %d",
		"ui.shop_ledger": "店鋪帳本",
		"ui.no_appraisals": "尚無鑑定紀錄。",
		"ui.ledger_entry": "第 %d 天：%s -> %s",
		"ui.result_detail_title": "鑑定結果詳情 %d/%d",
		"ui.result_detail_empty": "尚無鑑定結果詳情。",
		"ui.result_detail_body": "異物：%s\n決策：%s\n結果：%s\n現金：%+d\n聲望：%+d\n後果：%s",
		"ui.back_to_shop": "返回店鋪",
		"ui.magnifier": "放大鏡",
		"ui.uv_lamp": "紫外燈",
		"ui.thermometer": "溫度計",
		"ui.temperature": "溫度：%.1f C",
		"ui.appraisal_notes": "鑑定筆記",
		"ui.note_mag": "- 放大：%s",
		"ui.note_uv": "- UV：%s",
		"ui.note_temp": "- 溫度：%s",
		"ui.sell": "出售",
		"ui.seal": "封印",
		"ui.discard": "丟棄",
		"ui.detail_previous": "上一筆",
		"ui.detail_next": "下一筆",
		"decision.sell": "出售",
		"decision.seal": "封存",
		"decision.discard": "丟棄",
		"ui.correct_result": "正確：%s 已安全處理。",
		"ui.wrong_result": "錯誤：%s 應該%s，而不是%s。",
		"ui.cash_delta": "現金：%+d",
		"ui.reputation_delta": "聲望：%+d",
		"ui.next_day": "下一天",
		"ui.return_to_menu": "返回選單",
		"ui.run_summary": "流程總結",
		"ui.handled_count": "已處理：%d/%d 件異物",
		"ui.final_cash": "最終現金：%d",
		"ui.final_reputation": "最終聲望：%d",
		"ui.last_report": "最後紀錄：%s",
		"ui.no_consequence": "沒有紀錄後果。",
		"upgrade.ledger_desk.buy": "升級帳冊桌（-120）",
		"upgrade.ledger_desk.status_locked": "帳冊桌：可花費 %d 現金升級來源紀錄。",
		"upgrade.ledger_desk.status_unlocked": "帳冊桌已升級：顧客備註會加入來源紀錄。",
		"upgrade.ledger_desk.provenance": "來源紀錄：已交叉核對前持有人與流通筆記。",
		"outcome.correct": "正確處理",
		"outcome.cursed_sale": "詛咒出售",
		"outcome.uncontained_discard": "未收容丟棄",
		"outcome.bad_appraisal": "錯誤鑑定",
		"fallback.customer_note": "顧客備註",
		"fallback.customer_body": "一位顧客正在等待鑑定。",
		"fallback.risk_hint": "風險提示：未知",
		"fallback.consequence": "顧客沒有評論，只把鑑定備註歸檔。",
		"fallback.wrong_event": "%s 在錯誤鑑定後擾動了店鋪。",
		"item.oddity_0001.display_name": "低語茶杯",
		"item.oddity_0001.description": "一只白瓷茶杯，即使在明亮店燈下也異常冰冷。",
		"item.oddity_0001.magnifier_clue": "細裂紋在杯身周圍形成淡淡的螺旋。",
		"item.oddity_0001.uv_clue": "杯沿附近隱藏的環形印記在紫外光下泛藍。",
		"item.oddity_0001.thermometer_clue": "茶杯讀數遠低於室溫。",
		"item.oddity_0001.wrong_event_text": "如果出售，買家會帶著凍傷回來，店鋪聲望受損。",
		"item.oddity_0002.display_name": "鏡面硬幣",
		"item.oddity_0002.description": "一枚暗淡銀幣，幣面映出慢一秒的房間。",
		"item.oddity_0002.magnifier_clue": "透過放大鏡看時，鑄造日期會沿著邊緣反向重複。",
		"item.oddity_0002.uv_clue": "紫外光會顯出第二組漂浮在幣面上的姓名縮寫。",
		"item.oddity_0002.thermometer_clue": "硬幣讓桌面形成完美冷圈，但周圍空氣仍然溫暖。",
		"item.oddity_0002.wrong_event_text": "若讓它流出店外，硬幣會帶著明天日期的收據回到上鎖錢匣。",
		"item.oddity_0003.display_name": "灰燼音樂盒",
		"item.oddity_0003.description": "一個燒焦的音樂盒，蓋子關上時圓筒仍會喀噠作響。",
		"item.oddity_0003.magnifier_clue": "梳齒間塞滿灰燼，卻沒有任何灰落在桌面上。",
		"item.oddity_0003.uv_clue": "紫外光下，盒蓋底部有燒出的「帶我回家」。",
		"item.oddity_0003.thermometer_clue": "只有圓筒轉動時，音樂盒才會降溫。",
		"item.oddity_0003.wrong_event_text": "若被保存或賣出，午夜後空嬰兒房會再次響起曲調。",
		"item.oddity_0004.display_name": "冰冷黃銅鑰匙",
		"item.oddity_0004.description": "一把黃銅鑰匙，匙弓塞著地窖污垢，齒形每次看都像少了一段重複。",
		"item.oddity_0004.magnifier_clue": "只有最先進入鎖孔的齒面覆著新霜。",
		"item.oddity_0004.uv_clue": "紫外光會在匙弓上顯出一條地窖平面線。",
		"item.oddity_0004.thermometer_clue": "匙弓比匙身更冷，像是握柄被留在屋外。",
		"item.oddity_0004.wrong_event_text": "若它離開保護盒，附近的鎖會在 3:04 自行打開，再從錯的一側鎖上。",
		"item.oddity_0005.display_name": "玻璃義眼",
		"item.oddity_0005.description": "一顆放在外科醫師盒中的拋光玻璃義眼，令人不安但有完整登錄。",
		"item.oddity_0005.magnifier_clue": "製作者標記完整，虹膜細痕來自醫療配戴工具。",
		"item.oddity_0005.uv_clue": "紫外光下只看見乾淨序號，沒有儀式痕跡。",
		"item.oddity_0005.thermometer_clue": "即使被拿起檢查，義眼仍接近室溫。",
		"item.oddity_0005.wrong_event_text": "若被藏起，合法買家會取消交易，並傳出店家破壞無害古物的流言。",
		"item.oddity_0006.display_name": "黑蠟燭",
		"item.oddity_0006.description": "一支黑色禮拜堂蠟燭，無火時燭芯仍發熱，隱約有簽名的氣味。",
		"item.oddity_0006.magnifier_clue": "蠟痕不是往下流，而是往燭芯方向上爬。",
		"item.oddity_0006.uv_clue": "紫外光顯出環繞底座的一圈指印，像聚集的人群。",
		"item.oddity_0006.thermometer_clue": "燈光移開後，蠟燭反而變得更熱。",
		"item.oddity_0006.wrong_event_text": "若被保留或賣出，只要有人在店附近說出名字，燭芯就會點燃。",
		"item.oddity_0007.display_name": "蟲蛀布偶",
		"item.oddity_0007.description": "一個破舊布偶，不斷從縫補過太多次的縫線掉出灰色布屑。",
		"item.oddity_0007.magnifier_clue": "縫好的笑嘴用了好幾件不同衣物拆下的線。",
		"item.oddity_0007.uv_clue": "紫外光在裙背顯出小手掌壓痕。",
		"item.oddity_0007.thermometer_clue": "布偶最冷的位置在胸口縫線，而不是裸露布料。",
		"item.oddity_0007.wrong_event_text": "若讓它散著離開，線頭會在兒童房牆上拼出名字。",
		"item.oddity_0008.display_name": "銀製喪鈴",
		"item.oddity_0008.description": "一只失去光澤的銀製喪鈴，鈴舌被綁住，緞帶褪成棺襯般的灰色。",
		"item.oddity_0008.magnifier_clue": "鈴舌用黑線綁住，但放大鏡下仍能看見鈴身震動。",
		"item.oddity_0008.uv_clue": "紫外光在鈴口內側顯出刮出的姓名縮寫。",
		"item.oddity_0008.thermometer_clue": "鈴緣比最後被碰過的握柄更冷。",
		"item.oddity_0008.wrong_event_text": "若處置錯誤，每扇上鎖窗外都會傳來送葬隊伍的聲音。",
		"item.oddity_0009.display_name": "裂紋手鏡",
		"item.oddity_0009.description": "一面有裂紋的化妝間手鏡，剝落的銀背像第二張臉。",
		"item.oddity_0009.magnifier_clue": "中央裂紋先切開倒映的人臉，才切開玻璃。",
		"item.oddity_0009.uv_clue": "紫外光下沒有製作者標記，只有銀背翹起處形成的第二隻眼。",
		"item.oddity_0009.thermometer_clue": "只有鏡面被蓋住時，它才會回到室溫。",
		"item.oddity_0009.wrong_event_text": "若保持完整，鏡子被遮住後仍會留下第二個倒影。",
		"item.oddity_0010.display_name": "紅線軸",
		"item.oddity_0010.description": "一卷來自媒人桌上的紅線軸，仍連著兩張未結清的帳單。",
		"item.oddity_0010.magnifier_clue": "細小繩結標示成對姓名縮寫，而不是警告或日期。",
		"item.oddity_0010.uv_clue": "紫外光在紙芯上顯出對平的帳目數字。",
		"item.oddity_0010.thermometer_clue": "紅線像剛被握過的布料一樣微溫，但線軸核心正常。",
		"item.oddity_0010.wrong_event_text": "若被鎖起或丟掉，紅線會在打烊後把無關物件綁在一起。",
		"customer.oddity_0001.title": "顧客備註：發抖的女繼承人",
		"customer.oddity_0001.body": "黎明前送來一只包好的茶杯。信差拒絕第二次觸碰它。",
		"customer.oddity_0001.risk_hint": "風險提示：寒意轉移",
		"customer.oddity_0002.title": "顧客備註：鐘錶匠",
		"customer.oddity_0002.body": "一枚硬幣出現在上鎖的錢匣裡，映出不存在的房間。",
		"customer.oddity_0002.risk_hint": "風險提示：延遲倒影",
		"customer.oddity_0003.title": "顧客備註：遺產執行人",
		"customer.oddity_0003.body": "清點遺物時，這個音樂盒明明沒有上弦卻自己播放。",
		"customer.oddity_0003.risk_hint": "風險提示：自奏機構",
		"customer.oddity_0004.title": "顧客備註：夜班門房",
		"customer.oddity_0004.body": "一把黃銅鑰匙來自上鎖的地窖門，冷到連信封都發麻。",
		"customer.oddity_0004.risk_hint": "風險提示：與室溫不符",
		"customer.oddity_0005.title": "顧客備註：退休外科醫師",
		"customer.oddity_0005.body": "一顆玻璃義眼在密封器械盒中被發現，正朝上凝視。",
		"customer.oddity_0005.risk_hint": "風險提示：醫療來源清楚，表面仍凝視",
		"customer.oddity_0006.title": "顧客備註：禮拜堂看管人",
		"customer.oddity_0006.body": "一支黑蠟燭在未使用的禮拜堂登記冊旁被發現，像是冷冷燃燒著。",
		"customer.oddity_0006.risk_hint": "風險提示：注意移開後熱度升高",
		"customer.oddity_0007.title": "顧客備註：寄宿學校女舍監",
		"customer.oddity_0007.body": "一個布偶在宿舍箱子裡被發現，外面裹著脫落的布料碎片。",
		"customer.oddity_0007.risk_hint": "風險提示：兒童房寒痕，縫線活躍",
		"customer.oddity_0008.title": "顧客備註：殯儀館主管",
		"customer.oddity_0008.body": "一只銀鈴在密封棺木抽屜內被發現，那裡本應是空的。",
		"customer.oddity_0008.risk_hint": "風險提示：鈴舌被綁，仍在震動",
		"customer.oddity_0009.title": "顧客備註：劇院遺孀",
		"customer.oddity_0009.body": "一面裂紋手鏡來自午夜後會映出掌聲的化妝間。",
		"customer.oddity_0009.risk_hint": "風險提示：分裂倒影，遮蓋後才回溫",
		"customer.oddity_0010.title": "顧客備註：媒人",
		"customer.oddity_0010.body": "打烊後，有人發現一卷紅線軸把兩本帳簿綁在一起。",
		"customer.oddity_0010.risk_hint": "風險提示：帳目成對，紅線微溫",
		"consequence.oddity_0001.seal": "顧客沒有帶走茶杯就離開了",
		"consequence.oddity_0001.sell": "買家抱怨霜痕爬滿了收據",
		"consequence.oddity_0001.discard": "被丟棄的茶杯帶著新冰回到門階上。",
		"consequence.oddity_0002.seal": "鐘錶匠收下封印包後，不再聽見延遲的回聲。",
		"consequence.oddity_0002.sell": "買家匆忙付款，但門口的倒影慢了一拍。",
		"consequence.oddity_0002.discard": "鈴聲響過一次後，硬幣又滾回櫃檯下。",
		"consequence.oddity_0003.seal": "遺產執行人紀錄說，走廊裡的曲調終於停止了。",
		"consequence.oddity_0003.sell": "買家回報午夜後空嬰兒房裡傳來音樂。",
		"consequence.oddity_0003.discard": "音樂盒被安靜地移走了",
		"consequence.oddity_0004.seal": "門房回報地窖門保持關閉，鑰匙也停止結霜。",
		"consequence.oddity_0004.sell": "買家說屋內所有鎖都會在 3:04 自行彈開。",
		"consequence.oddity_0004.discard": "鑰匙帶著新冰層回到店門墊下。",
		"consequence.oddity_0005.seal": "封存盒在快遞離開前一直從內側輕敲。",
		"consequence.oddity_0005.sell": "買家回報，義眼被放進展示盒後就安靜下來。",
		"consequence.oddity_0005.discard": "打烊前，玻璃義眼又滾回櫃台下方。",
		"consequence.oddity_0006.seal": "封存蠟燭安靜前，先在盒內留下溫熱煤痕。",
		"consequence.oddity_0006.sell": "買家說每當有人說出名字，蠟燭就會自行點燃。",
		"consequence.oddity_0006.discard": "燭芯被掐滅後，蠟燭塌成無害蠟塊。",
		"consequence.oddity_0007.seal": "封存盒扣緊後，布偶不再掉落布料。",
		"consequence.oddity_0007.sell": "買家回報，鬆開的線頭會在兒童房牆上拼出名字。",
		"consequence.oddity_0007.discard": "打烊後，布偶被發現直坐在垃圾桶裡。",
		"consequence.oddity_0008.seal": "封存鈴輕輕響了一聲，隨後在盒中安靜下來。",
		"consequence.oddity_0008.sell": "買家聽見每扇上鎖窗外都有葬禮隊伍經過。",
		"consequence.oddity_0008.discard": "每當店裡安靜下來，垃圾箱裡的鈴就會響起。",
		"consequence.oddity_0009.seal": "封存鏡從內側起霧，並持續映出另一個房間。",
		"consequence.oddity_0009.sell": "買家回報，自己的倒影會比本人更早離開房間。",
		"consequence.oddity_0009.discard": "破鏡在丟棄後變暗，再也不映出任何東西。",
		"consequence.oddity_0010.seal": "封存的線軸不斷從盒內在鎖扣周圍打結。",
		"consequence.oddity_0010.sell": "買家說紅線安靜地把兩封遺失的信牽到一起。",
		"consequence.oddity_0010.discard": "被丟棄的紅線纏住垃圾桶並拒絕燃燒。",
		"ending.frost_sale.title": "壞結局：霜凍交易",
	},
}

var current_locale := DEFAULT_LOCALE


func _ready() -> void:
	set_locale(DEFAULT_LOCALE)


func set_locale(locale_code: String) -> void:
	if locale_code in SUPPORTED_LOCALES:
		current_locale = locale_code
	else:
		current_locale = DEFAULT_LOCALE


func text(key: String) -> String:
	var locale_table: Dictionary = TEXT.get(current_locale, TEXT[DEFAULT_LOCALE])
	if locale_table.has(key):
		return str(locale_table[key])
	var default_table: Dictionary = TEXT[DEFAULT_LOCALE]
	return str(default_table.get(key, key))


func format_text(key: String, values: Array) -> String:
	return text(key) % values


func item_text(item_id: String, field_name: String, fallback: String = "") -> String:
	var key := "item.%s.%s" % [item_id, field_name]
	var translated := text(key)
	if translated == key:
		return fallback
	return translated
